<div class="alert alert-block alert-info">
<b>WDI Inventory: </b> 
   137 indicators in Topic 6: Environment

<b>Output: </b> 
    WDI Availability of Data in Topic 6: Environment (2000-2021)</div>

In [1]:
import os
import pandas as pd
import wbgapi as wb # https://github.com/tgherzog/wbgapi
import plotly.express as px
import plotly.graph_objects as go
import datetime
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
# Define your own folder 
out_dir = os.path.join(os.path.expanduser('~'), 'Documents/Websites/JavierParada.github.io/Inventory/')
print(out_dir)

/Users/javierparada/Documents/Websites/JavierParada.github.io/Inventory/

## Check for recent updates in each of the 65 databases

In [3]:
# Check date for last update of WDI 2021-09-15
ListOfDict = list(wb.source.list())
Databases = pd.DataFrame(ListOfDict)
print("There are {} databases available.".format(len(Databases)))
print("{} was last updated on {}.".format(ListOfDict[1]['name'],ListOfDict[1]['lastupdated']))
Databases['lastupdated'] = pd.to_datetime(Databases['lastupdated'])
Databases.sort_values(by='lastupdated', ascending=False).head()

There are 67 databases available.
World Development Indicators was last updated on 2021-09-15.

,id,lastupdated,name,code,databid,description,url,dataavailability,metadataavailability,concepts
66,87,2021-10-03,Country Climate and Development Report (CCDR),CCD,3736,,,Y,Y,3
2,3,2021-09-27,Worldwide Governance Indicators,WGI,1181,,,Y,Y,3
8,14,2021-09-27,Gender Statistics,GDS,283,,,Y,Y,3
65,86,2021-09-24,Global Jobs Indicators Database (JOIN),JON,3735,,,Y,Y,3
38,57,2021-09-24,WDI Database Archives,WDA,1277,,,Y,Y,4

## 21 topics, 1,443 indicators in WDI, 135 in topic 6 Environment

In [4]:
# 21 topics
pd.DataFrame(list(wb.topic.list())).head()

,id,value,sourceNote
0,1,Agriculture & Rural Development,For the 70 percent of the world's poor who liv...
1,2,Aid Effectiveness,Aid effectiveness is the impact that aid has i...
2,3,Economy & Growth,Economic growth is central to economic develop...
3,4,Education,Education is one of the most powerful instrume...
4,5,Energy & Mining,The world economy needs ever-increasing amount...

In [5]:
others = ['EG.ELC.ACCS.RU.ZS', 'EG.ELC.ACCS.UR.ZS']
desc_others = pd.DataFrame(list(wb.series.list(others)))
desc = pd.DataFrame(list(wb.series.list(db=2, topic=6)))
desc = desc.append(desc_others)
desc = desc.rename({'id': 'variable', 'value':'description'}, axis=1)
desc = desc.sort_values(by='variable', ascending=True)
desc.to_csv('desc.csv')

In [6]:
list(wb.series.list(db=2, topic=6))

[{'id': 'EG.CFT.ACCS.ZS',
  'value': 'Access to clean fuels and technologies for cooking (% of population)'},
 {'id': 'NY.ADJ.SVNG.GN.ZS',
  'value': 'Adjusted net savings, including particulate emission damage (% of GNI)'},
 {'id': 'NY.ADJ.SVNG.CD',
  'value': 'Adjusted net savings, including particulate emission damage (current US$)'},
 {'id': 'NY.ADJ.DCO2.GN.ZS',
  'value': 'Adjusted savings: carbon dioxide damage (% of GNI)'},
 {'id': 'NY.ADJ.DCO2.CD',
  'value': 'Adjusted savings: carbon dioxide damage (current US$)'},
 {'id': 'NY.ADJ.DKAP.GN.ZS',
  'value': 'Adjusted savings: consumption of fixed capital (% of GNI)'},
 {'id': 'NY.ADJ.AEDU.GN.ZS',
  'value': 'Adjusted savings: education expenditure (% of GNI)'},
 {'id': 'NY.ADJ.AEDU.CD',
  'value': 'Adjusted savings: education expenditure (current US$)'},
 {'id': 'NY.ADJ.DNGY.GN.ZS',
  'value': 'Adjusted savings: energy depletion (% of GNI)'},
 {'id': 'NY.ADJ.DMIN.CD',
  'value': 'Adjusted savings: mineral depletion (current US$)'},
 {'id': 'NY.ADJ.DFOR.GN.ZS',
  'value': 'Adjusted savings: net forest depletion (% of GNI)'},
 {'id': 'NY.ADJ.DFOR.CD',
  'value': 'Adjusted savings: net forest depletion (current US$)'},
 {'id': 'NY.ADJ.NNAT.CD',
  'value': 'Adjusted savings: net national savings (current US$)'},
 {'id': 'EN.ATM.METH.AG.ZS',
  'value': 'Agricultural methane emissions (% of total)'},
 {'id': 'EN.ATM.METH.AG.KT.CE',
  'value': 'Agricultural methane emissions (thousand metric tons of CO2 equivalent)'},
 {'id': 'EN.ATM.NOXE.AG.ZS',
  'value': 'Agricultural nitrous oxide emissions (% of total)'},
 {'id': 'ER.H2O.FWAG.ZS',
  'value': 'Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)'},
 {'id': 'ER.H2O.FWIN.ZS',
  'value': 'Annual freshwater withdrawals, industry (% of total freshwater withdrawal)'},
 {'id': 'ER.H2O.FWTL.K3',
  'value': 'Annual freshwater withdrawals, total (billion cubic meters)'},
 {'id': 'ER.FSH.AQUA.MT', 'value': 'Aquaculture production (metric tons)'},
 {'id': 'EN.ATM.CO2E.KD.GD',
  'value': 'CO2 emissions (kg per 2010 US$ of GDP)'},
 {'id': 'EN.ATM.CO2E.PP.GD.KD',
  'value': 'CO2 emissions (kg per 2017 PPP $ of GDP)'},
 {'id': 'EN.ATM.CO2E.PP.GD', 'value': 'CO2 emissions (kg per PPP $ of GDP)'},
 {'id': 'EN.ATM.CO2E.KT', 'value': 'CO2 emissions (kt)'},
 {'id': 'EN.ATM.CO2E.PC', 'value': 'CO2 emissions (metric tons per capita)'},
 {'id': 'EN.CO2.ETOT.ZS',
  'value': 'CO2 emissions from electricity and heat production, total (% of total fuel combustion)'},
 {'id': 'EN.ATM.CO2E.LF.ZS',
  'value': 'CO2 emissions from liquid fuel consumption (% of total)'},
 {'id': 'EN.ATM.CO2E.LF.KT',
  'value': 'CO2 emissions from liquid fuel consumption (kt)'},
 {'id': 'EN.CO2.MANF.ZS',
  'value': 'CO2 emissions from manufacturing industries and construction (% of total fuel combustion)'},
 {'id': 'EN.CO2.BLDG.ZS',
  'value': 'CO2 emissions from residential buildings and commercial and public services (% of total fuel combustion)'},
 {'id': 'EN.ATM.CO2E.SF.ZS',
  'value': 'CO2 emissions from solid fuel consumption (% of total)'},
 {'id': 'EN.ATM.CO2E.SF.KT',
  'value': 'CO2 emissions from solid fuel consumption (kt)'},
 {'id': 'EN.ATM.CO2E.EG.ZS',
  'value': 'CO2 intensity (kg per kg of oil equivalent energy use)'},
 {'id': 'EG.ELC.RNWX.ZS',
  'value': 'Electricity production from renewable sources, excluding hydroelectric (% of total)'},
 {'id': 'EN.ATM.METH.EG.ZS',
  'value': 'Energy related methane emissions (% of total)'},
 {'id': 'AG.LND.FRST.ZS', 'value': 'Forest area (% of land area)'},
 {'id': 'AG.LND.FRST.K2', 'value': 'Forest area (sq. km)'},
 {'id': 'NY.GDP.FRST.RT.ZS', 'value': 'Forest rents (% of GDP)'},
 {'id': 'EN.CLC.GHGR.MT.CE',
  'value': 'GHG net emissions/removals by LUCF (Mt of CO2 equivalent)'},
 {'id': 'EN.ATM.HFCG.KT.CE',
  'value': 'HFC gas emissions (thousand metric tons of CO2 equivalent)'},
 {'id': 'AG.LND.TOTL.K2', 'value': 'Land area (sq. km)'},
 {'id': 'AG.LND.EL5M.ZS',
  'value': 'Land area where elevation is below 5 meters (% of total land area)'},
 {'id': 'ER.H2O.FWST.ZS',
  'value': 'Level of water stress: freshwater withdrawal as a proportion of available freshwater resources'},
 {'id': 'EN.ATM.METH.EG.KT.CE',
  'value': 'Methane emissions in energy sector (thousand metric tons of CO2 equivalent)'},
 {'id': 'SH.STA.AIRP.P5',
  'value': 'Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)'},
 {'id': 'SH.STA.POIS.P5.MA',
  'value': 'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)'},
 {'id': 'NY.GDP.NGAS.RT.ZS', 'value': 'Natural gas rents (% of GDP)'},
 {'id': 'EN.ATM.NOXE.EG.ZS',
  'value': 'Nitrous oxide emissions in energy sector (% of total)'},
 {'id': 'EN.ATM.NOXE.EG.KT.CE',
  'value': 'Nitrous oxide emissions in energy sector (thousand metric tons of CO2 equivalent)'},
 {'id': 'NY.GDP.PETR.RT.ZS', 'value': 'Oil rents (% of GDP)'},
 {'id': 'EN.ATM.GHGO.KT.CE',
  'value': 'Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)'},
 {'id': 'SH.STA.BASS.UR.ZS',
  'value': 'People using at least basic sanitation services, urban (% of urban population)'},
 {'id': 'SH.H2O.SMDW.ZS',
  'value': 'People using safely managed drinking water services (% of population)'},
 {'id': 'SH.STA.SMSS.ZS',
  'value': 'People using safely managed sanitation services (% of population)'},
 {'id': 'SH.STA.SMSS.RU.ZS',
  'value': 'People using safely managed sanitation services, rural (% of rural population)'},
 {'id': 'SH.STA.HYGN.UR.ZS',
  'value': 'People with basic handwashing facilities including soap and water, urban (% of urban population)'},
 {'id': 'EN.ATM.PFCG.KT.CE',
  'value': 'PFC gas emissions (thousand metric tons of CO2 equivalent)'},
 {'id': 'EN.ATM.PM25.MC.T1.ZS',
  'value': 'PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-1 value (% of total)'},
 {'id': 'EN.ATM.PM25.MC.T2.ZS',
  'value': 'PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-2 value (% of total)'},
 {'id': 'EN.ATM.PM25.MC.T3.ZS',
  'value': 'PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-3 value (% of total)'},
 {'id': 'EN.POP.SLUM.UR.ZS',
  'value': 'Population living in slums (% of urban population)'},
 {'id': 'EG.FEC.RNEW.ZS',
  'value': 'Renewable energy consumption (% of total final energy consumption)'},
 {'id': 'ER.H2O.INTR.PC',
  'value': 'Renewable internal freshwater resources per capita (cubic meters)'},
 {'id': 'AG.LND.EL5M.RU.ZS',
  'value': 'Rural land area where elevation is below 5 meters (% of total land area)'},
 {'id': 'EN.ATM.GHGT.ZG',
  'value': 'Total greenhouse gas emissions (% change from 1990)'},
 {'id': 'NY.GDP.TOTL.RT.ZS',
  'value': 'Total natural resources rents (% of GDP)'},
 {'id': 'AG.LND.TOTL.UR.K2', 'value': 'Urban land area (sq. km)'},
 {'id': 'AG.LND.EL5M.UR.ZS',
  'value': 'Urban land area where elevation is below 5 meters (% of total land area)'},
 {'id': 'ER.GDP.FWTL.M3.KD',
  'value': 'Water productivity, total (constant 2010 US$ GDP per cubic meter of total freshwater withdrawal)'},
 {'id': 'EG.ELC.ACCS.ZS', 'value': 'Access to electricity (% of population)'},
 {'id': 'NY.ADJ.SVNX.GN.ZS',
  'value': 'Adjusted net savings, excluding particulate emission damage (% of GNI)'},
 {'id': 'NY.ADJ.SVNX.CD',
  'value': 'Adjusted net savings, excluding particulate emission damage (current US$)'},
 {'id': 'NY.ADJ.DKAP.CD',
  'value': 'Adjusted savings: consumption of fixed capital (current US$)'},
 {'id': 'NY.ADJ.DNGY.CD',
  'value': 'Adjusted savings: energy depletion (current US$)'},
 {'id': 'NY.ADJ.ICTR.GN.ZS',
  'value': 'Adjusted savings: gross savings (% of GNI)'},
 {'id': 'NY.ADJ.DMIN.GN.ZS',
  'value': 'Adjusted savings: mineral depletion (% of GNI)'},
 {'id': 'NY.ADJ.NNAT.GN.ZS',
  'value': 'Adjusted savings: net national savings (% of GNI)'},
 {'id': 'NY.ADJ.DPEM.GN.ZS',
  'value': 'Adjusted savings: particulate emission damage (% of GNI)'},
 {'id': 'NY.ADJ.DPEM.CD',
  'value': 'Adjusted savings: particulate emission damage (current US$)'},
 {'id': 'AG.LND.AGRI.ZS', 'value': 'Agricultural land (% of land area)'},
 {'id': 'EN.ATM.NOXE.AG.KT.CE',
  'value': 'Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)'},
 {'id': 'ER.H2O.FWDM.ZS',
  'value': 'Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)'},
 {'id': 'ER.H2O.FWTL.ZS',
  'value': 'Annual freshwater withdrawals, total (% of internal resources)'},
 {'id': 'AG.LND.ARBL.ZS', 'value': 'Arable land (% of land area)'},
 {'id': 'AG.LND.PRCP.MM',
  'value': 'Average precipitation in depth (mm per year)'},
 {'id': 'EN.BIR.THRD.NO', 'value': 'Bird species, threatened'},
 {'id': 'ER.FSH.CAPT.MT',
  'value': 'Capture fisheries production (metric tons)'},
 {'id': 'EN.ATM.CO2E.GF.ZS',
  'value': 'CO2 emissions from gaseous fuel consumption (% of total)'},
 {'id': 'EN.ATM.CO2E.GF.KT',
  'value': 'CO2 emissions from gaseous fuel consumption (kt)'},
 {'id': 'EN.CO2.OTHX.ZS',
  'value': 'CO2 emissions from other sectors, excluding residential buildings and commercial and public services (% of total fuel combustion)'},
 {'id': 'EN.CO2.TRAN.ZS',
  'value': 'CO2 emissions from transport (% of total fuel combustion)'},
 {'id': 'NY.GDP.COAL.RT.ZS', 'value': 'Coal rents (% of GDP)'},
 {'id': 'EN.CLC.DRSK.XQ',
  'value': 'Disaster risk reduction progress score (1-5 scale; 5=best)'},
 {'id': 'EN.CLC.MDAT.ZS',
  'value': 'Droughts, floods, extreme temperatures (% of population, average 1990-2009)'},
 {'id': 'EG.ELC.FOSL.ZS',
  'value': 'Electricity production from oil, gas and coal sources (% of total)'},
 {'id': 'EG.ELC.RNWX.KH',
  'value': 'Electricity production from renewable sources, excluding hydroelectric (kWh)'},
 {'id': 'EG.EGY.PRIM.PP.KD',
  'value': 'Energy intensity level of primary energy (MJ/$2011 PPP GDP)'},
 {'id': 'EN.FSH.THRD.NO', 'value': 'Fish species, threatened'},
 {'id': 'EN.MAM.THRD.NO', 'value': 'Mammal species, threatened'},
 {'id': 'ER.MRN.PTMR.ZS',
  'value': 'Marine protected areas (% of territorial waters)'},
 {'id': 'EN.ATM.METH.ZG', 'value': 'Methane emissions (% change from 1990)'},
 {'id': 'EN.ATM.METH.KT.CE',
  'value': 'Methane emissions (kt of CO2 equivalent)'},
 {'id': 'NY.GDP.MINR.RT.ZS', 'value': 'Mineral rents (% of GDP)'},
 {'id': 'SH.STA.POIS.P5',
  'value': 'Mortality rate attributed to unintentional poisoning (per 100,000 population)'},
 {'id': 'SH.STA.POIS.P5.FE',
  'value': 'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)'},
 {'id': 'SH.STA.WASH.P5',
  'value': 'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)'},
 {'id': 'EN.ATM.NOXE.ZG',
  'value': 'Nitrous oxide emissions (% change from 1990)'},
 {'id': 'EN.ATM.NOXE.KT.CE',
  'value': 'Nitrous oxide emissions (thousand metric tons of CO2 equivalent)'},
 {'id': 'EN.ATM.GHGO.ZG',
  'value': 'Other greenhouse gas emissions (% change from 1990)'},
 {'id': 'SH.STA.ODFC.ZS',
  'value': 'People practicing open defecation (% of population)'},
 {'id': 'SH.STA.ODFC.RU.ZS',
  'value': 'People practicing open defecation, rural (% of rural population)'},
 {'id': 'SH.STA.ODFC.UR.ZS',
  'value': 'People practicing open defecation, urban (% of urban population)'},
 {'id': 'SH.H2O.BASW.ZS',
  'value': 'People using at least basic drinking water services (% of population)'},
 {'id': 'SH.H2O.BASW.RU.ZS',
  'value': 'People using at least basic drinking water services, rural (% of rural population)'},
 {'id': 'SH.H2O.BASW.UR.ZS',
  'value': 'People using at least basic drinking water services, urban (% of urban population)'},
 {'id': 'SH.STA.BASS.ZS',
  'value': 'People using at least basic sanitation services (% of population)'},
 {'id': 'SH.STA.BASS.RU.ZS',
  'value': 'People using at least basic sanitation services, rural (% of rural population)'},
 {'id': 'SH.H2O.SMDW.RU.ZS',
  'value': 'People using safely managed drinking water services, rural (% of rural population)'},
 {'id': 'SH.H2O.SMDW.UR.ZS',
  'value': 'People using safely managed drinking water services, urban (% of urban population)'},
 {'id': 'SH.STA.SMSS.UR.ZS',
  'value': 'People using safely managed sanitation services, urban (% of urban population)'},
 {'id': 'SH.STA.HYGN.ZS',
  'value': 'People with basic handwashing facilities including soap and water (% of population)'},
 {'id': 'SH.STA.HYGN.RU.ZS',
  'value': 'People with basic handwashing facilities including soap and water, rural (% of rural population)'},
 {'id': 'EN.HPT.THRD.NO', 'value': 'Plant species (higher), threatened'},
 {'id': 'EN.ATM.PM25.MC.M3',
  'value': 'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)'},
 {'id': 'EN.ATM.PM25.MC.ZS',
  'value': 'PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)'},
 {'id': 'EN.POP.EL5M.ZS',
  'value': 'Population living in areas where elevation is below 5 meters (% of total population)'},
 {'id': 'EG.ELC.RNEW.ZS',
  'value': 'Renewable electricity output (% of total electricity output)'},
 {'id': 'ER.H2O.INTR.K3',
  'value': 'Renewable internal freshwater resources, total (billion cubic meters)'},
 {'id': 'AG.LND.TOTL.RU.K2', 'value': 'Rural land area (sq. km)'},
 {'id': 'AG.LND.EL5M.RU.K2',
  'value': 'Rural land area where elevation is below 5 meters (sq. km)'},
 {'id': 'EN.POP.EL5M.RU.ZS',
  'value': 'Rural population living in areas where elevation is below 5 meters (% of total population)'},
 {'id': 'EN.ATM.SF6G.KT.CE',
  'value': 'SF6 gas emissions (thousand metric tons of CO2 equivalent)'},
 {'id': 'AG.SRF.TOTL.K2', 'value': 'Surface area (sq. km)'},
 {'id': 'ER.PTD.TOTL.ZS',
  'value': 'Terrestrial and marine protected areas (% of total territorial area)'},
 {'id': 'ER.LND.PTLD.ZS',
  'value': 'Terrestrial protected areas (% of total land area)'},
 {'id': 'ER.FSH.PROD.MT', 'value': 'Total fisheries production (metric tons)'},
 {'id': 'EN.ATM.GHGT.KT.CE',
  'value': 'Total greenhouse gas emissions (kt of CO2 equivalent)'},
 {'id': 'AG.LND.EL5M.UR.K2',
  'value': 'Urban land area where elevation is below 5 meters (sq. km)'},
 {'id': 'EN.POP.EL5M.UR.ZS',
  'value': 'Urban population living in areas where elevation is below 5 meters (% of total population)'}]

# Environment 135

In [7]:
# List of indicators
others = ['EG.ELC.ACCS.RU.ZS', 'EG.ELC.ACCS.UR.ZS']
environment135 = sorted(list(wb.topic.members(6)) + others)
len(environment135)

141

In [8]:
environment135

['AG.LND.AGRI.ZS',
 'AG.LND.ARBL.ZS',
 'AG.LND.EL5M.RU.K2',
 'AG.LND.EL5M.RU.ZS',
 'AG.LND.EL5M.UR.K2',
 'AG.LND.EL5M.UR.ZS',
 'AG.LND.EL5M.ZS',
 'AG.LND.FRST.K2',
 'AG.LND.FRST.ZS',
 'AG.LND.PRCP.MM',
 'AG.LND.TOTL.K2',
 'AG.LND.TOTL.RU.K2',
 'AG.LND.TOTL.UR.K2',
 'AG.SRF.TOTL.K2',
 'EG.CFT.ACCS.ZS',
 'EG.EGY.PRIM.PP.KD',
 'EG.ELC.ACCS.RU.ZS',
 'EG.ELC.ACCS.UR.ZS',
 'EG.ELC.ACCS.ZS',
 'EG.ELC.FOSL.ZS',
 'EG.ELC.RNEW.ZS',
 'EG.ELC.RNWX.KH',
 'EG.ELC.RNWX.ZS',
 'EG.FEC.RNEW.ZS',
 'EN.ATM.CO2E.EG.ZS',
 'EN.ATM.CO2E.GF.KT',
 'EN.ATM.CO2E.GF.ZS',
 'EN.ATM.CO2E.KD.GD',
 'EN.ATM.CO2E.KT',
 'EN.ATM.CO2E.LF.KT',
 'EN.ATM.CO2E.LF.ZS',
 'EN.ATM.CO2E.PC',
 'EN.ATM.CO2E.PP.GD',
 'EN.ATM.CO2E.PP.GD.KD',
 'EN.ATM.CO2E.SF.KT',
 'EN.ATM.CO2E.SF.ZS',
 'EN.ATM.GHGO.KT.CE',
 'EN.ATM.GHGO.ZG',
 'EN.ATM.GHGT.KT.CE',
 'EN.ATM.GHGT.ZG',
 'EN.ATM.HFCG.KT.CE',
 'EN.ATM.METH.AG.KT.CE',
 'EN.ATM.METH.AG.ZS',
 'EN.ATM.METH.EG.KT.CE',
 'EN.ATM.METH.EG.ZS',
 'EN.ATM.METH.KT.CE',
 'EN.ATM.METH.ZG',
 'EN.ATM.NOXE.AG.KT.CE',
 'EN.ATM.NOXE.AG.ZS',
 'EN.ATM.NOXE.EG.KT.CE',
 'EN.ATM.NOXE.EG.ZS',
 'EN.ATM.NOXE.KT.CE',
 'EN.ATM.NOXE.ZG',
 'EN.ATM.PFCG.KT.CE',
 'EN.ATM.PM25.MC.M3',
 'EN.ATM.PM25.MC.T1.ZS',
 'EN.ATM.PM25.MC.T2.ZS',
 'EN.ATM.PM25.MC.T3.ZS',
 'EN.ATM.PM25.MC.ZS',
 'EN.ATM.SF6G.KT.CE',
 'EN.BIR.THRD.NO',
 'EN.CLC.DRSK.XQ',
 'EN.CLC.GHGR.MT.CE',
 'EN.CLC.MDAT.ZS',
 'EN.CO2.BLDG.ZS',
 'EN.CO2.ETOT.ZS',
 'EN.CO2.MANF.ZS',
 'EN.CO2.OTHX.ZS',
 'EN.CO2.TRAN.ZS',
 'EN.FSH.THRD.NO',
 'EN.HPT.THRD.NO',
 'EN.MAM.THRD.NO',
 'EN.POP.EL5M.RU.ZS',
 'EN.POP.EL5M.UR.ZS',
 'EN.POP.EL5M.ZS',
 'EN.POP.SLUM.UR.ZS',
 'ER.FSH.AQUA.MT',
 'ER.FSH.CAPT.MT',
 'ER.FSH.PROD.MT',
 'ER.GDP.FWTL.M3.KD',
 'ER.H2O.FWAG.ZS',
 'ER.H2O.FWDM.ZS',
 'ER.H2O.FWIN.ZS',
 'ER.H2O.FWST.ZS',
 'ER.H2O.FWTL.K3',
 'ER.H2O.FWTL.ZS',
 'ER.H2O.INTR.K3',
 'ER.H2O.INTR.PC',
 'ER.LND.PTLD.ZS',
 'ER.MRN.PTMR.ZS',
 'ER.PTD.TOTL.ZS',
 'NY.ADJ.AEDU.CD',
 'NY.ADJ.AEDU.GN.ZS',
 'NY.ADJ.DCO2.CD',
 'NY.ADJ.DCO2.GN.ZS',
 'NY.ADJ.DFOR.CD',
 'NY.ADJ.DFOR.GN.ZS',
 'NY.ADJ.DKAP.CD',
 'NY.ADJ.DKAP.GN.ZS',
 'NY.ADJ.DMIN.CD',
 'NY.ADJ.DMIN.GN.ZS',
 'NY.ADJ.DNGY.CD',
 'NY.ADJ.DNGY.GN.ZS',
 'NY.ADJ.DPEM.CD',
 'NY.ADJ.DPEM.GN.ZS',
 'NY.ADJ.ICTR.GN.ZS',
 'NY.ADJ.NNAT.CD',
 'NY.ADJ.NNAT.GN.ZS',
 'NY.ADJ.SVNG.CD',
 'NY.ADJ.SVNG.GN.ZS',
 'NY.ADJ.SVNX.CD',
 'NY.ADJ.SVNX.GN.ZS',
 'NY.GDP.COAL.RT.ZS',
 'NY.GDP.FRST.RT.ZS',
 'NY.GDP.MINR.RT.ZS',
 'NY.GDP.NGAS.RT.ZS',
 'NY.GDP.PETR.RT.ZS',
 'NY.GDP.TOTL.RT.ZS',
 'SH.H2O.BASW.RU.ZS',
 'SH.H2O.BASW.UR.ZS',
 'SH.H2O.BASW.ZS',
 'SH.H2O.SMDW.RU.ZS',
 'SH.H2O.SMDW.UR.ZS',
 'SH.H2O.SMDW.ZS',
 'SH.STA.AIRP.P5',
 'SH.STA.BASS.RU.ZS',
 'SH.STA.BASS.UR.ZS',
 'SH.STA.BASS.ZS',
 'SH.STA.HYGN.RU.ZS',
 'SH.STA.HYGN.UR.ZS',
 'SH.STA.HYGN.ZS',
 'SH.STA.ODFC.RU.ZS',
 'SH.STA.ODFC.UR.ZS',
 'SH.STA.ODFC.ZS',
 'SH.STA.POIS.P5',
 'SH.STA.POIS.P5.FE',
 'SH.STA.POIS.P5.MA',
 'SH.STA.SMSS.RU.ZS',
 'SH.STA.SMSS.UR.ZS',
 'SH.STA.SMSS.ZS',
 'SH.STA.WASH.P5']

In [9]:
# Includes TWN
countries = sorted(list(wb.region.members('WLD')))
countries.remove("TWN")
len(countries)

217

In [10]:
file_excel = "countries217.csv"
wikipedia = pd.read_csv(os.path.join(out_dir,file_excel))
wikipedia = wikipedia.rename({'Code': 'economy'}, axis=1)
wikipedia.head()

,Original order,economy,Country,Order,Continent,Wikipedia
0,1,AFG,Afghanistan,102,Asia,https://en.wikipedia.org/wiki/Afghanistan
1,2,ALB,Albania,75,Europe,https://en.wikipedia.org/wiki/Albania
2,3,DZA,Algeria,141,Africa,https://en.wikipedia.org/wiki/Algeria
3,4,ASM,American Samoa,A1,Other,https://en.wikipedia.org/wiki/American_Samoa
4,5,AND,Andorra,62,Europe,https://en.wikipedia.org/wiki/Andorra

In [11]:
appended_data = []
for count, variable in enumerate(environment135, start=1):
    print(count, variable)
    df = wb.data.DataFrame(series = variable, 
                    economy = countries, 
                    time = range(2000, 2022, 1), 
                    db=2, labels=True).reset_index()
    df["variable"] = variable
    print("Done")
    appended_data.append(df)
    
appended_data = pd.concat(appended_data)
# appended_data.to_excel('appended.xlsx')

1 AG.LND.AGRI.ZS
Done
2 AG.LND.ARBL.ZS
Done
3 AG.LND.EL5M.RU.K2
Done
4 AG.LND.EL5M.RU.ZS
Done
5 AG.LND.EL5M.UR.K2
Done
6 AG.LND.EL5M.UR.ZS
Done
7 AG.LND.EL5M.ZS
Done
8 AG.LND.FRST.K2
Done
9 AG.LND.FRST.ZS
Done
10 AG.LND.PRCP.MM
Done
11 AG.LND.TOTL.K2
Done
12 AG.LND.TOTL.RU.K2
Done
13 AG.LND.TOTL.UR.K2
Done
14 AG.SRF.TOTL.K2
Done
15 EG.CFT.ACCS.ZS
Done
16 EG.EGY.PRIM.PP.KD
Done
17 EG.ELC.ACCS.RU.ZS
Done
18 EG.ELC.ACCS.UR.ZS
Done
19 EG.ELC.ACCS.ZS
Done
20 EG.ELC.FOSL.ZS
Done
21 EG.ELC.RNEW.ZS
Done
22 EG.ELC.RNWX.KH
Done
23 EG.ELC.RNWX.ZS
Done
24 EG.FEC.RNEW.ZS
Done
25 EN.ATM.CO2E.EG.ZS
Done
26 EN.ATM.CO2E.GF.KT
Done
27 EN.ATM.CO2E.GF.ZS
Done
28 EN.ATM.CO2E.KD.GD
Done
29 EN.ATM.CO2E.KT
Done
30 EN.ATM.CO2E.LF.KT
Done
31 EN.ATM.CO2E.LF.ZS
Done
32 EN.ATM.CO2E.PC
Done
33 EN.ATM.CO2E.PP.GD
Done
34 EN.ATM.CO2E.PP.GD.KD
Done
35 EN.ATM.CO2E.SF.KT
Done
36 EN.ATM.CO2E.SF.ZS
Done
37 EN.ATM.GHGO.KT.CE
Done
38 EN.ATM.GHGO.ZG
Done
39 EN.ATM.GHGT.KT.CE
Done
40 EN.ATM.GHGT.ZG
Done
41 EN.ATM.HFCG.KT.CE
Done
42 EN.ATM.METH.AG.KT.CE
Done
43 EN.ATM.METH.AG.ZS
Done
44 EN.ATM.METH.EG.KT.CE
Done
45 EN.ATM.METH.EG.ZS
Done
46 EN.ATM.METH.KT.CE
Done
47 EN.ATM.METH.ZG
Done
48 EN.ATM.NOXE.AG.KT.CE
Done
49 EN.ATM.NOXE.AG.ZS
Done
50 EN.ATM.NOXE.EG.KT.CE
Done
51 EN.ATM.NOXE.EG.ZS
Done
52 EN.ATM.NOXE.KT.CE
Done
53 EN.ATM.NOXE.ZG
Done
54 EN.ATM.PFCG.KT.CE
Done
55 EN.ATM.PM25.MC.M3
Done
56 EN.ATM.PM25.MC.T1.ZS
Done
57 EN.ATM.PM25.MC.T2.ZS
Done
58 EN.ATM.PM25.MC.T3.ZS
Done
59 EN.ATM.PM25.MC.ZS
Done
60 EN.ATM.SF6G.KT.CE
Done
61 EN.BIR.THRD.NO
Done
62 EN.CLC.DRSK.XQ
Done
63 EN.CLC.GHGR.MT.CE
Done
64 EN.CLC.MDAT.ZS
Done
65 EN.CO2.BLDG.ZS
Done
66 EN.CO2.ETOT.ZS
Done
67 EN.CO2.MANF.ZS
Done
68 EN.CO2.OTHX.ZS
Done
69 EN.CO2.TRAN.ZS
Done
70 EN.FSH.THRD.NO
Done
71 EN.HPT.THRD.NO
Done
72 EN.MAM.THRD.NO
Done
73 EN.POP.EL5M.RU.ZS
Done
74 EN.POP.EL5M.UR.ZS
Done
75 EN.POP.EL5M.ZS
Done
76 EN.POP.SLUM.UR.ZS
Done
77 ER.FSH.AQUA.MT
Done
78 ER.FSH.CAPT.MT
Done
79 ER.FSH.PROD.MT
Done
80 ER.GDP.FWTL.M3.KD
Done
81 ER.H2O.FWAG.ZS
Done
82 ER.H2O.FWDM.ZS
Done
83 ER.H2O.FWIN.ZS
Done
84 ER.H2O.FWST.ZS
Done
85 ER.H2O.FWTL.K3
Done
86 ER.H2O.FWTL.ZS
Done
87 ER.H2O.INTR.K3
Done
88 ER.H2O.INTR.PC
Done
89 ER.LND.PTLD.ZS
Done
90 ER.MRN.PTMR.ZS
Done
91 ER.PTD.TOTL.ZS
Done
92 NY.ADJ.AEDU.CD
Done
93 NY.ADJ.AEDU.GN.ZS
Done
94 NY.ADJ.DCO2.CD
Done
95 NY.ADJ.DCO2.GN.ZS
Done
96 NY.ADJ.DFOR.CD
Done
97 NY.ADJ.DFOR.GN.ZS
Done
98 NY.ADJ.DKAP.CD
Done
99 NY.ADJ.DKAP.GN.ZS
Done
100 NY.ADJ.DMIN.CD
Done
101 NY.ADJ.DMIN.GN.ZS
Done
102 NY.ADJ.DNGY.CD
Done
103 NY.ADJ.DNGY.GN.ZS
Done
104 NY.ADJ.DPEM.CD
Done
105 NY.ADJ.DPEM.GN.ZS
Done
106 NY.ADJ.ICTR.GN.ZS
Done
107 NY.ADJ.NNAT.CD
Done
108 NY.ADJ.NNAT.GN.ZS
Done
109 NY.ADJ.SVNG.CD
Done
110 NY.ADJ.SVNG.GN.ZS
Done
111 NY.ADJ.SVNX.CD
Done
112 NY.ADJ.SVNX.GN.ZS
Done
113 NY.GDP.COAL.RT.ZS
Done
114 NY.GDP.FRST.RT.ZS
Done
115 NY.GDP.MINR.RT.ZS
Done
116 NY.GDP.NGAS.RT.ZS
Done
117 NY.GDP.PETR.RT.ZS
Done
118 NY.GDP.TOTL.RT.ZS
Done
119 SH.H2O.BASW.RU.ZS
Done
120 SH.H2O.BASW.UR.ZS
Done
121 SH.H2O.BASW.ZS
Done
122 SH.H2O.SMDW.RU.ZS
Done
123 SH.H2O.SMDW.UR.ZS
Done
124 SH.H2O.SMDW.ZS
Done
125 SH.STA.AIRP.P5
Done
126 SH.STA.BASS.RU.ZS
Done
127 SH.STA.BASS.UR.ZS
Done
128 SH.STA.BASS.ZS
Done
129 SH.STA.HYGN.RU.ZS
Done
130 SH.STA.HYGN.UR.ZS
Done
131 SH.STA.HYGN.ZS
Done
132 SH.STA.ODFC.RU.ZS
Done
133 SH.STA.ODFC.UR.ZS
Done
134 SH.STA.ODFC.ZS
Done
135 SH.STA.POIS.P5
Done
136 SH.STA.POIS.P5.FE
Done
137 SH.STA.POIS.P5.MA
Done
138 SH.STA.SMSS.RU.ZS
Done
139 SH.STA.SMSS.UR.ZS
Done
140 SH.STA.SMSS.ZS
Done
141 SH.STA.WASH.P5
Done

In [17]:
tableau = appended_data.groupby('variable').count().reset_index()
tableau[['CETS1','CETS2','CETS3','CETS4','CETS5','CETS6']] = tableau['variable'].str.split(expand=True, pat='.')
tableau = tableau.merge(desc, left_on='variable', right_on='variable', suffixes=('_left', '_right')) 
tableau["row"] = tableau['variable'] +": "+ tableau['description']
tableau.set_index('variable', inplace=True)
#tableau = tableau[tableau["CETS3"] == "EL5M"]
tableau

,economy,Country,YR2000,YR2001,YR2002,YR2003,YR2004,YR2005,YR2006,YR2007,YR2008,YR2009,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,CETS1,CETS2,CETS3,CETS4,CETS5,CETS6,description,row
variable,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AG.LND.AGRI.ZS,217,217,206,206,206,206,206,206,208,209,208,208,208,210,210,210,210,210,210,209,209,0,0,AG,LND,AGRI,ZS,None,None,Agricultural land (% of land area),AG.LND.AGRI.ZS: Agricultural land (% of land a...
AG.LND.ARBL.ZS,217,217,204,204,204,204,204,204,206,207,206,206,206,207,207,207,207,207,206,205,205,0,0,AG,LND,ARBL,ZS,None,None,Arable land (% of land area),AG.LND.ARBL.ZS: Arable land (% of land area)
AG.LND.EL5M.RU.K2,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,RU,K2,None,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.K2: Rural land area where eleva...
AG.LND.EL5M.RU.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,RU,ZS,None,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.ZS: Rural land area where eleva...
AG.LND.EL5M.UR.K2,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,UR,K2,None,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2: Urban land area where eleva...
AG.LND.EL5M.UR.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,UR,ZS,None,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.ZS: Urban land area where eleva...
AG.LND.EL5M.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,ZS,None,None,Land area where elevation is below 5 meters (%...,AG.LND.EL5M.ZS: Land area where elevation is b...
AG.LND.FRST.K2,217,217,214,210,210,210,210,210,210,210,210,210,214,214,214,214,214,214,214,214,214,210,210,AG,LND,FRST,K2,None,None,Forest area (sq. km),AG.LND.FRST.K2: Forest area (sq. km)
AG.LND.FRST.ZS,217,217,213,210,210,210,210,210,210,210,210,210,213,214,214,214,214,214,214,214,214,210,210,AG,LND,FRST,ZS,None,None,Forest area (% of land area),AG.LND.FRST.ZS: Forest area (% of land area)
AG.LND.PRCP.MM,217,217,0,0,180,0,0,0,0,180,0,0,0,0,182,0,2,0,0,180,0,0,0,AG,LND,PRCP,MM,None,None,Average precipitation in depth (mm per year),AG.LND.PRCP.MM: Average precipitation in depth...
AG.LND.TOTL.K2,217,217,216,216,216,216,216,216,216,216,216,216,216,217,217,217,217,217,217,217,216,216,216,AG,LND,TOTL,K2,None,None,Land area (sq. km),AG.LND.TOTL.K2: Land area (sq. km)
AG.LND.TOTL.RU.K2,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,TOTL,RU,K2,None,Rural land area (sq. km),AG.LND.TOTL.RU.K2: Rural land area (sq. km)
AG.LND.TOTL.UR.K2,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,AG,LND,TOTL,UR,K2,None,Urban land area (sq. km),AG.LND.TOTL.UR.K2: Urban land area (sq. km)
AG.SRF.TOTL.K2,217,217,215,215,215,215,215,215,215,215,215,215,215,217,217,217,217,217,217,217,216,0,0,AG,SRF,TOTL,K2,None,None,Surface area (sq. km),AG.SRF.TOTL.K2: Surface area (sq. km)
EG.CFT.ACCS.ZS,217,217,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,0,0,0,0,EG,CFT,ACCS,ZS,None,None,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS: Access to clean fuels and tech...
EG.EGY.PRIM.PP.KD,217,217,190,190,191,191,191,192,192,192,192,192,192,192,193,193,192,191,0,0,0,0,0,EG,EGY,PRIM,PP,KD,None,Energy intensity level of primary energy (MJ/$...,EG.EGY.PRIM.PP.KD: Energy intensity level of p...
EG.ELC.ACCS.RU.ZS,217,217,174,183,189,192,195,196,199,198,201,201,204,206,205,207,208,210,208,207,210,209,0,EG,ELC,ACCS,RU,ZS,None,"Access to electricity, rural (% of rural popul...","EG.ELC.ACCS.RU.ZS: Access to electricity, rura..."
EG.ELC.ACCS.UR.ZS,217,217,188,194,200,200,202,205,207,207,209,212,213,214,214,214,214,214,214,214,214,214,0,EG,ELC,ACCS,UR,ZS,None,"Access to electricity, urban (% of urban popul...","EG.ELC.ACCS.UR.ZS: Access to electricity, urba..."
EG.ELC.ACCS.ZS,217,217,190,196,202,202,204,207,209,209,211,214,215,216,216,216,216,216,216,216,216,216,0,EG,ELC,ACCS,ZS,None,None,Access to electricity (% of population),EG.ELC.ACCS.ZS: Access to electricity (% of po...
EG.ELC.FOSL.ZS,217,217,139,139,139,139,139,140,140,140,140,140,140,140,141,141,141,141,0,0,0,0,0,EG,ELC,FOSL,ZS,None,None,"Electricity production from oil, gas and coal ...",EG.ELC.FOSL.ZS: Electricity production from oi...
EG.ELC.RNEW.ZS,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,217,1,1,1,1,0,EG,ELC,RNEW,ZS,None,None,Renewable electricity output (% of total elect...,EG.ELC.RNEW.ZS: Renewable electricity output (...
EG.ELC.RNWX.KH,217,217,139,139,139,139,139,140,140,140,140,140,140,140,141,141,141,141,0,0,0,0,0,EG,ELC,RNWX,KH,None,None,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH: Electricity production from re...
EG.ELC.RNWX.ZS,217,217,139,139,139,139,139,140,140,140,140,140,140,140,141,141,141,141,0,0,0,0,0,EG,ELC,RNWX,ZS,None,None,"Electricity production from renewable sources,...",EG.ELC.RNWX.ZS: Electricity production from re...
EG.FEC.RNEW.ZS,217,217,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,0,0,EG,FEC,RNEW,ZS,None,None,Renewable energy consumption (% of total final...,EG.FEC.RNEW.ZS: Renewable energy consumption (...
EN.ATM.CO2E.EG.ZS,217,217,136,136,136,136,166,167,167,167,137,137,137,137,138,138,132,34,0,0,0,0,0,EN,ATM,CO2E,EG,ZS,None,CO2 intensity (kg per kg of oil equivalent ene...,EN.ATM.CO2E.EG.ZS: CO2 intensity (kg per kg of...
EN.ATM.CO2E.GF.KT,217,217,199,199,200,200,200,201,202,203,204,204,204,204,207,207,207,204,204,0,0,0,0,EN,ATM,CO2E,GF,KT,None,CO2 emissions from gaseous fuel consumption (kt),EN.ATM.CO2E.GF.KT: CO2 emissions from gaseous ...
EN.ATM.CO2E.GF.ZS,217,217,186,186,187,187,187,188,189,190,190,190,190,190,191,191,191,189,189,0,0,0,0,EN,ATM,CO2E,GF,ZS,None,CO2 emissions from gaseous fuel consumption (%...,EN.ATM.CO2E.GF.ZS: CO2 emissions from gaseous ...
EN.ATM.CO2E.KD.GD,217,217,182,183,184,184,185,185,185,185,186,186,188,186,185,185,185,184,183,183,183,0,0,EN,ATM,CO2E,KD,GD,None,CO2 emissions (kg per 2010 US$ of GDP),EN.ATM.CO2E.KD.GD: CO2 emissions (kg per 2010 ...
EN.ATM.CO2E.KT,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,CO2E,KT,None,None,CO2 emissions (kt),EN.ATM.CO2E.KT: CO2 emissions (kt)
EN.ATM.CO2E.LF.KT,217,217,199,199,200,200,200,201,202,203,204,204,204,204,207,207,207,204,204,0,0,0,0,EN,ATM,CO2E,LF,KT,None,CO2 emissions from liquid fuel consumption (kt),EN.ATM.CO2E.LF.KT: CO2 emissions from liquid f...
EN.ATM.CO2E.LF.ZS,217,217,186,186,187,187,187,188,189,190,190,190,190,190,191,191,191,189,189,0,0,0,0,EN,ATM,CO2E,LF,ZS,None,CO2 emissions from liquid fuel consumption (% ...,EN.ATM.CO2E.LF.ZS: CO2 emissions from liquid f...
EN.ATM.CO2E.PC,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,CO2E,PC,None,None,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC: CO2 emissions (metric tons per...
EN.ATM.CO2E.PP.GD,217,217,180,181,182,182,183,183,183,183,184,184,184,184,182,184,183,183,182,182,182,0,0,EN,ATM,CO2E,PP,GD,None,CO2 emissions (kg per PPP $ of GDP),EN.ATM.CO2E.PP.GD: CO2 emissions (kg per PPP $...
EN.ATM.CO2E.PP.GD.KD,217,217,177,178,179,179,180,180,180,180,180,180,180,180,180,182,182,182,182,182,182,0,0,EN,ATM,CO2E,PP,GD,KD,CO2 emissions (kg per 2017 PPP $ of GDP),EN.ATM.CO2E.PP.GD.KD: CO2 emissions (kg per 20...
EN.ATM.CO2E.SF.KT,217,217,199,199,200,200,200,201,202,203,204,204,204,204,207,207,207,204,204,0,0,0,0,EN,ATM,CO2E,SF,KT,None,CO2 emissions from solid fuel consumption (kt),EN.ATM.CO2E.SF.KT: CO2 emissions from solid fu...
EN.ATM.CO2E.SF.ZS,217,217,186,186,187,187,187,188,189,190,190,190,190,190,191,191,191,189,189,0,0,0,0,EN,ATM,CO2E,SF,ZS,None,CO2 emissions from solid fuel consumption (% o...,EN.ATM.CO2E.SF.ZS: CO2 emissions from solid fu...
EN.ATM.GHGO.KT.CE,217,217,183,183,183,183,183,183,183,183,183,183,183,184,184,180,180,180,180,0,0,0,0,EN,ATM,GHGO,KT,CE,None,"Other greenhouse gas emissions, HFC, PFC and S...",EN.ATM.GHGO.KT.CE: Other greenhouse gas emissi...
EN.ATM.GHGO.ZG,217,217,188,188,188,188,188,187,188,188,188,188,188,188,188,0,0,0,0,0,0,0,0,EN,ATM,GHGO,ZG,None,None,Other greenhouse gas emissions (% change from ...,EN.ATM.GHGO.ZG: Other greenhouse gas emissions...
EN.ATM.GHGT.KT.CE,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,GHGT,KT,CE,None,Total greenhouse gas emissions (kt of CO2 equi...,EN.ATM.GHGT.KT.CE: Total greenhouse gas emissi...
EN.ATM.GHGT.ZG,217,217,180,179,180,179,180,178,177,178,174,174,172,174,174,0,0,0,0,0,0,0,0,EN,ATM,GHGT,ZG,None,None,Total greenhouse gas emissions (% change from ...,EN.ATM.GHGT.ZG: Total greenhouse gas emissions...
EN.ATM.HFCG.KT.CE,217,217,135,0,0,0,0,135,0,0,135,0,137,0,0,0,0,0,0,0,0,0,0,EN,ATM,HFCG,KT,CE,None,HFC gas emissions (thousand metric tons of CO2...,EN.ATM.HFCG.KT.CE: HFC gas emissions (thousand...
EN.ATM.METH.AG.KT.CE,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,METH,AG,KT,CE,Agricultural methane emissions (thousand metri...,EN.ATM.METH.AG.KT.CE: Agricultural methane emi...
EN.ATM.METH.AG.ZS,217,217,190,190,190,190,190,190,190,190,190,0,0,0,0,0,0,0,0,0,0,0,0,EN,ATM,METH,AG,ZS,None,Agricultural methane emissions (% of total),EN.ATM.METH.AG.ZS: Agricultural methane emissi...
EN.ATM.METH.EG.KT.CE,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,METH,EG,KT,CE,Methane emissions in energy sector (thousand m...,EN.ATM.METH.EG.KT.CE: Methane emissions in ene...
EN.ATM.METH.EG.ZS,217,217,190,190,190,190,190,190,190,190,190,0,0,0,0,0,0,0,0,0,0,0,0,EN,ATM,METH,EG,ZS,None,Energy related methane emissions (% of total),EN.ATM.METH.EG.ZS: Energy related methane emis...
EN.ATM.METH.KT.CE,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,METH,KT,CE,None,Methane emissions (kt of CO2 equivalent),EN.ATM.METH.KT.CE: Methane emissions (kt of CO...
EN.ATM.METH.ZG,217,217,204,204,204,204,204,204,204,204,204,204,204,204,204,0,0,0,0,0,0,0,0,EN,ATM,METH,ZG,None,None,Methane emissions (% change from 1990),EN.ATM.METH.ZG: Methane emissions (% change fr...
EN.ATM.NOXE.AG.KT.CE,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,NOXE,AG,KT,CE,Agricultural nitrous oxide emissions (thousand...,EN.ATM.NOXE.AG.KT.CE: Agricultural nitrous oxi...
EN.ATM.NOXE.AG.ZS,217,217,185,185,185,185,185,185,185,185,185,0,0,0,0,0,0,0,0,0,0,0,0,EN,ATM,NOXE,AG,ZS,None,Agricultural nitrous oxide emissions (% of total),EN.ATM.NOXE.AG.ZS: Agricultural nitrous oxide ...
EN.ATM.NOXE.EG.KT.CE,217,217,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,0,0,EN,ATM,NOXE,EG,KT,CE,Nitrous oxide emissions in energy sector (thou...,EN.ATM.NOXE.EG.KT.CE: Nitrous oxide emissions ...
EN.ATM.NOXE.EG.ZS,217,217,185,185,185,185,185,185,185,185,185,0,0,0,0,0,0,0,0,0,0,0,0,EN,ATM,NOXE,EG,ZS,None,Nitrous oxide emissions in energy sector (% of...,EN.ATM.NOXE.EG.ZS: Nitrous oxide emissions in ...
EN.ATM.NOXE.KT.CE,217,217,190,190,190,190,190,190,190,190,190,190,190,191,191,191,191,191,191,191,191,0,0,EN,ATM,NOXE,KT,CE,None,Nitrous oxide emissions (thousand metric tons ...,EN.ATM.NOXE.KT.CE: Nitrous oxide emissions (th...
EN.ATM.NOXE.ZG,217,217,205,205,205,205,205,205,205,205,205,205,205,205,205,0,0,0,0,0,0,0,0,EN,ATM,NOXE,ZG,None,None,Nitrous oxide emissions (% change from 1990),EN.ATM.NOXE.ZG: Nitrous oxide emissions (% cha...
EN.ATM.PFCG.KT.CE,217,217,135,0,0,0,0,135,0,0,135,0,137,0,0,0,0,0,0,0,0,0,0,EN,ATM,PFCG,KT,CE,None,PFC gas emissions (thousand metric tons of CO2...,EN.ATM.PFCG.KT.CE: PFC gas emissions (thousand...
EN.ATM.PM25.MC.M3,217,217,194,0,0,0,0,194,0,0,0,0,194,194,194,194,194,194,194,194,0,0,0,EN,ATM,PM25,MC,M3,None,"PM2.5 air pollution, mean annual exposure (mic...","EN.ATM.PM25.MC.M3: PM2.5 air pollution, mean a..."
EN.ATM.PM25.MC.T1.ZS,217,217,194,0,0,0,0,194,0,0,0,0,194,194,194,194,194,194,194,194,0,0,0,EN,ATM,PM25,MC,T1,ZS,"PM2.5 pollution, population exposed to levels ...","EN.ATM.PM25.MC.T1.ZS: PM2.5 pollution, populat..."
EN.ATM.PM25.MC.T2.ZS,217,217,194,0,0,0,0,194,0,0,0,0,194,194,194,194,194,194,194,194,0,0,0,EN,ATM,PM25,MC,T2,ZS,"PM2.5 pollution, population exposed to levels ...","EN.ATM.PM25.MC.T2.ZS: PM2.5 pollution, populat..."
EN.ATM.PM25.MC.T3.ZS,217,217,194,0,0,0,0,194,0,0,0,0,194,194,194,194,194,194,194,194,0,0,0,EN,ATM,PM25,MC,T3,ZS,"PM2.5 pollution, population exposed to levels ...","EN.ATM.PM25.MC.T3.ZS: PM2.5 pollution, populat..."
EN.ATM.PM25.MC.ZS,217,217,194,0,0,0,0,194,0,0,0,0,194,194,194,194,194,194,194,194,0,0,0,EN,ATM,PM25,MC,ZS,None,"PM2.5 air pollution, population exposed to lev...","EN.ATM.PM25.MC.ZS: PM2.5 air pollution, popula..."
EN.ATM.SF6G.KT.CE,217,217,135,0,0,0,0,135,0,0,135,0,137,0,0,0,0,0,0,0,0,0,0,EN,ATM,SF6G,KT,CE,None,SF6 gas emissions (thousand metric tons of CO2...,EN.ATM.SF6G.KT.CE: SF6 gas emissions (thousand...
EN.BIR.THRD.NO,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,215,0,0,EN,BIR,THRD,NO,None,None,"Bird species, threatened","EN.BIR.THRD.NO: Bird species, threatened"
EN.CLC.DRSK.XQ,217,217,0,0,0,0,0,0,0,0,0,0,0,83,0,0,0,0,0,0,0,0,0,EN,CLC,DRSK,XQ,None,None,Disaster risk reduction progress score (1-5 sc...,EN.CLC.DRSK.XQ: Disaster risk reduction progre...
EN.CLC.GHGR.MT.CE,217,217,58,42,43,45,45,47,43,43,41,41,0,0,0,0,0,0,0,0,0,0,0,EN,CLC,GHGR,MT,CE,None,GHG net emissions/removals by LUCF (Mt of CO2 ...,EN.CLC.GHGR.MT.CE: GHG net emissions/removals ...
EN.CLC.MDAT.ZS,217,217,0,0,0,0,0,0,0,0,0,168,0,0,0,0,0,0,0,0,0,0,0,EN,CLC,MDAT,ZS,None,None,"Droughts, floods, extreme temperatures (% of p...","EN.CLC.MDAT.ZS: Droughts, floods, extreme temp..."
EN.CO2.BLDG.ZS,217,217,140,140,140,140,140,141,141,141,141,141,141,141,142,142,142,0,0,0,0,0,0,EN,CO2,BLDG,ZS,None,None,CO2 emissions from residential buildings and c...,EN.CO2.BLDG.ZS: CO2 emissions from residential...
EN.CO2.ETOT.ZS,217,217,140,140,140,140,140,141,141,141,141,141,141,141,142,142,142,0,0,0,0,0,0,EN,CO2,ETOT,ZS,None,None,CO2 emissions from electricity and heat produc...,EN.CO2.ETOT.ZS: CO2 emissions from electricity...
EN.CO2.MANF.ZS,217,217,140,140,140,140,140,141,141,141,141,141,141,141,142,142,142,0,0,0,0,0,0,EN,CO2,MANF,ZS,None,None,CO2 emissions from manufacturing industries an...,EN.CO2.MANF.ZS: CO2 emissions from manufacturi...
EN.CO2.OTHX.ZS,217,217,140,140,140,140,140,141,141,141,141,141,141,141,142,142,142,0,0,0,0,0,0,EN,CO2,OTHX,ZS,None,None,"CO2 emissions from other sectors, excluding re...",EN.CO2.OTHX.ZS: CO2 emissions from other secto...
EN.CO2.TRAN.ZS,217,217,140,140,140,140,140,141,141,141,141,141,141,141,142,142,142,0,0,0,0,0,0,EN,CO2,TRAN,ZS,None,None,CO2 emissions from transport (% of total fuel ...,EN.CO2.TRAN.ZS: CO2 emissions from transport (...
EN.FSH.THRD.NO,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,215,0,0,EN,FSH,THRD,NO,None,None,"Fish species, threatened","EN.FSH.THRD.NO: Fish species, threatened"
EN.HPT.THRD.NO,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,215,0,0,EN,HPT,THRD,NO,None,None,"Plant species (higher), threatened","EN.HPT.THRD.NO: Plant species (higher), threat..."
EN.MAM.THRD.NO,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,215,0,0,EN,MAM,THRD,NO,None,None,"Mammal species, threatened","EN.MAM.THRD.NO: Mammal species, threatened"
EN.POP.EL5M.RU.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,EN,POP,EL5M,RU,ZS,None,Rural population living in areas where elevati...,EN.POP.EL5M.RU.ZS: Rural population living in ...
EN.POP.EL5M.UR.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,EN,POP,EL5M,UR,ZS,None,Urban population living in areas where elevati...,EN.POP.EL5M.UR.ZS: Urban population living in ...
EN.POP.EL5M.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,EN,POP,EL5M,ZS,None,None,Population living in areas where elevation is ...,EN.POP.EL5M.ZS: Population living in areas whe...
EN.POP.SLUM.UR.ZS,217,217,49,0,0,0,0,83,0,0,0,0,50,0,0,0,94,0,117,0,122,0,0,EN,POP,SLUM,UR,ZS,None,Population living in slums (% of urban populat...,EN.POP.SLUM.UR.ZS: Population living in slums ...
ER.FSH.AQUA.MT,217,217,179,179,179,180,180,180,185,185,185,187,187,189,189,189,191,194,194,192,192,0,0,ER,FSH,AQUA,MT,None,None,Aquaculture production (metric tons),ER.FSH.AQUA.MT: Aquaculture production (metric...
ER.FSH.CAPT.MT,217,217,210,210,210,210,210,210,212,213,213,213,213,215,216,216,216,216,216,215,215,0,0,ER,FSH,CAPT,MT,None,None,Capture fisheries production (metric tons),ER.FSH.CAPT.MT: Capture fisheries production (...
ER.FSH.PROD.MT,217,217,210,210,210,210,210,210,212,213,213,213,213,215,216,216,216,216,216,215,215,0,0,ER,FSH,PROD,MT,None,None,Total fisheries production (metric tons),ER.FSH.PROD.MT: Total fisheries production (me...
ER.GDP.FWTL.M3.KD,217,217,0,1,158,0,0,2,0,167,0,0,0,0,174,0,1,0,0,172,0,0,0,ER,GDP,FWTL,M3,KD,None,"Water productivity, total (constant 2010 US$ G...","ER.GDP.FWTL.M3.KD: Water productivity, total (..."
ER.H2O.FWAG.ZS,217,217,0,1,158,0,0,1,0,168,0,0,0,0,177,0,1,0,0,178,0,0,0,ER,H2O,FWAG,ZS,None,None,"Annual freshwater withdrawals, agriculture (% ...","ER.H2O.FWAG.ZS: Annual freshwater withdrawals,..."
ER.H2O.FWDM.ZS,217,217,0,1,156,0,0,1,0,166,0,0,0,0,176,0,1,0,0,178,0,0,0,ER,H2O,FWDM,ZS,None,None,"Annual freshwater withdrawals, domestic (% of ...","ER.H2O.FWDM.ZS: Annual freshwater withdrawals,..."
ER.H2O.FWIN.ZS,217,217,0,1,155,0,0,1,0,164,0,0,0,0,175,0,1,0,0,177,0,0,0,ER,H2O,FWIN,ZS,None,None,"Annual freshwater withdrawals, industry (% of ...","ER.H2O.FWIN.ZS: Annual freshwater withdrawals,..."
ER.H2O.FWST.ZS,217,217,0,0,160,0,0,0,0,168,0,0,0,0,176,0,3,0,0,176,0,0,0,ER,H2O,FWST,ZS,None,None,Level of water stress: freshwater withdrawal a...,ER.H2O.FWST.ZS: Level of water stress: freshwa...
ER.H2O.FWTL.K3,217,217,0,1,162,0,0,2,0,171,0,0,0,0,179,0,1,0,0,179,0,0,0,ER,H2O,FWTL,K3,None,None,"Annual freshwater withdrawals, total (billion ...","ER.H2O.FWTL.K3: Annual freshwater withdrawals,..."
ER.H2O.FWTL.ZS,217,217,0,0,159,0,0,0,0,167,0,0,0,0,175,0,0,0,0,175,0,0,0,ER,H2O,FWTL,ZS,None,None,"Annual freshwater withdrawals, total (% of int...","ER.H2O.FWTL.ZS: Annual freshwater withdrawals,..."
ER.H2O.INTR.K3,217,217,0,0,181,0,0,0,0,182,0,0,0,0,182,0,1,0,0,181,0,0,0,ER,H2O,INTR,K3,None,None,"Renewable internal freshwater resources, total...",ER.H2O.INTR.K3: Renewable internal freshwater ...
ER.H2O.INTR.PC,217,217,0,0,181,0,0,0,0,182,0,0,0,0,182,0,1,0,0,181,0,0,0,ER,H2O,INTR,PC,None,None,Renewable internal freshwater resources per ca...,ER.H2O.INTR.PC: Renewable internal freshwater ...
ER.LND.PTLD.ZS,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,210,211,211,0,0,ER,LND,PTLD,ZS,None,None,Terrestrial protected areas (% of total land a...,ER.LND.PTLD.ZS: Terrestrial protected areas (%...
ER.MRN.PTMR.ZS,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,161,169,169,0,0,ER,MRN,PTMR,ZS,None,None,Marine protected areas (% of territorial waters),ER.MRN.PTMR.ZS: Marine protected areas (% of t...
ER.PTD.TOTL.ZS,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,211,210,210,0,0,ER,PTD,TOTL,ZS,None,None,Terrestrial and marine protected areas (% of t...,ER.PTD.TOTL.ZS: Terrestrial and marine protect...
NY.ADJ.AEDU.CD,217,217,181,180,182,182,183,183,184,185,184,185,185,187,186,186,187,186,185,184,182,175,0,NY,ADJ,AEDU,CD,None,None,Adjusted savings: education expenditure (curre...,NY.ADJ.AEDU.CD: Adjusted savings: education ex...
NY.ADJ.AEDU.GN.ZS,217,217,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,0,NY,ADJ,AEDU,GN,ZS,None,Adjusted savings: education expenditure (% of ...,NY.ADJ.AEDU.GN.ZS: Adjusted savings: education...
NY.ADJ.DCO2.CD,217,217,202,202,203,203,203,204,205,206,207,207,207,207,210,210,210,209,209,206,206,206,0,NY,ADJ,DCO2,CD,None,None,Adjusted savings: carbon dioxide damage (curre...,NY.ADJ.DCO2.CD: Adjusted savings: carbon dioxi...

In [18]:
counts = tableau[['CETS1','CETS2','CETS3','CETS4','CETS5']].value_counts().to_frame('counts')
counts.sort_values(by=['CETS1','CETS2','CETS3','CETS4','CETS5'], ascending=True)

                               counts
CETS1 CETS2 CETS3 CETS4 CETS5
AG    LND   EL5M  RU    K2          1
                        ZS          1
                  UR    K2          1
                        ZS          1
            TOTL  RU    K2          1
                  UR    K2          1
EG    EGY   PRIM  PP    KD          1
      ELC   ACCS  RU    ZS          1
                  UR    ZS          1
EN    ATM   CO2E  EG    ZS          1
                  GF    KT          1
                        ZS          1
                  KD    GD          1
                  LF    KT          1
                        ZS          1
                  PP    GD          2
                  SF    KT          1
                        ZS          1
            GHGO  KT    CE          1
            GHGT  KT    CE          1
            HFCG  KT    CE          1
            METH  AG    KT          1
                        ZS          1
                  EG    KT          1
                        ZS          1
                  KT    CE          1
            NOXE  AG    KT          1
                        ZS          1
                  EG    KT          1
                        ZS          1
                  KT    CE          1
            PFCG  KT    CE          1
            PM25  MC    M3          1
                        T1          1
                        T2          1
                        T3          1
                        ZS          1
            SF6G  KT    CE          1
      CLC   GHGR  MT    CE          1
      POP   EL5M  RU    ZS          1
                  UR    ZS          1
            SLUM  UR    ZS          1
ER    GDP   FWTL  M3    KD          1
NY    ADJ   AEDU  GN    ZS          1
            DCO2  GN    ZS          1
            DFOR  GN    ZS          1
            DKAP  GN    ZS          1
            DMIN  GN    ZS          1
            DNGY  GN    ZS          1
            DPEM  GN    ZS          1
            ICTR  GN    ZS          1
            NNAT  GN    ZS          1
            SVNG  GN    ZS          1
            SVNX  GN    ZS          1
      GDP   COAL  RT    ZS          1
            FRST  RT    ZS          1
            MINR  RT    ZS          1
            NGAS  RT    ZS          1
            PETR  RT    ZS          1
            TOTL  RT    ZS          1
SH    H2O   BASW  RU    ZS          1
                  UR    ZS          1
            SMDW  RU    ZS          1
                  UR    ZS          1
      STA   BASS  RU    ZS          1
                  UR    ZS          1
            HYGN  RU    ZS          1
                  UR    ZS          1
            ODFC  RU    ZS          1
                  UR    ZS          1
            POIS  P5    FE          1
                        MA          1
            SMSS  RU    ZS          1
                  UR    ZS          1

In [21]:
columns = ['YR2000', 'YR2001', 'YR2002','YR2003', 'YR2004', 'YR2005', 'YR2006', 'YR2007', 'YR2008', 'YR2009',
           'YR2010', 'YR2011', 'YR2012', 'YR2013', 'YR2014', 'YR2015', 'YR2016','YR2017', 'YR2018', 'YR2019', 'YR2020']

In [22]:
pd.options.display.float_format = '{:,.1f}'.format
percentages = tableau[columns]/217*100
data = percentages.values.round(1)

In [25]:
fig = px.imshow(data,
                labels=dict(x = "Year", y = "Indicator", color = "Available"),
                x = columns,
                y = tableau["row"].tolist(), 
                width=1500, height=3000,
                color_continuous_scale = "portland_r"
               )
fig.update_layout(
    title='WDI Availability of Data in Topic 6: Environment (2000-2021)',
    coloraxis_colorbar=dict(
    thicknessmode="pixels", thickness=70,
    lenmode="pixels", len=400,
    yanchor="top", y=.95,
    ticks="outside", ticksuffix=" %",
    dtick=5)
)
fig.update_xaxes(side="top")
fig.write_html("../WDIinventory.html")
fig.write_json("../WDIinventory.json", pretty=True)

<div class="alert alert-block alert-info">
October 4, 2021</div>

# Notes

https://stackoverflow.com/questions/64778606/plotly-heatmap-color-legend-i-subplothttps://stackoverflow.com/questions/64778606/plotly-heatmap-color-legend-i-subplot

df = wb.data.DataFrame(series = 'EG.ELC.ACCS.RU.ZS', 
                    economy=countries, 
                    time=range(2000, 2021, 1), 
                    db=2, labels=True).reset_index()

In [17]:
df = wb.data.DataFrame('EG.ELC.ACCS.ZS', wb.region.members('WLD'), time=range(2000, 2021, 1), labels=True)

In [18]:
wb.series.metadata.get('EG.ELC.ACCS.ZS', economies=['KEN', 'TZA'])

========
Series: EG.ELC.ACCS.ZS

Aggregationmethod: Weighted average
--------
Developmentrelevance: Maintaining reliable and secure electricity services while seeking to rapidly decarbonize power systems is a key challenge for countries throughout the world. More and more countries are becoming increasing dependent on reliable and secure electricity supplies to underpin economic growth and community prosperity. This reliance is set to grow as more efficient and less carbon intensive forms of power are developed and deployed to help decarbonize economies.

Energy is necessary for creating the conditions for economic growth. It is impossible to operate a factory, run a shop, grow crops or deliver goods to consumers without using some form of energy. Access to electricity is particularly crucial to human development as electricity is, in practice, indispensable for certain basic activities, such as lighting, refrigeration and the running of household appliances, and cannot easily be replaced by other forms of energy. Individuals' access to electricity is one of the most clear and un-distorted indication of a country's energy poverty status.

Electricity access is increasingly at the forefront of governments' preoccupations, especially in the developing countries. As a consequence, a lot of rural electrification programs and national electrification agencies have been created in these countries to monitor more accurately the needs and the status of rural development and electrification.

Use of energy is important in improving people's standard of living. But electricity generation also can damage the environment. Whether such damage occurs depends largely on how electricity is generated. For example, burning coal releases twice as much carbon dioxide - a major contributor to global warming - as does burning an equivalent amount of natural gas.
--------
IndicatorName: Access to electricity (% of population)
--------
License_Type: CC BY-4.0
--------
License_URL: https://datacatalog.worldbank.org/public-licenses#cc-by
--------
Longdefinition: Access to electricity is the percentage of population with access to electricity. Electrification data are collected from industry, national surveys and international sources.
--------
Periodicity: Annual
--------
Source: World Bank Global Electrification Database from "Tracking SDG 7: The Energy Progress Report" led jointly by the custodian agencies: the International Energy Agency (IEA), the International Renewable Energy Agency (IRENA), the United Nations Statistics Division (UNSD), the World Bank and the World Health Organization (WHO).
--------
Statisticalconceptandmethodology: Data for access to electricity are collected among different sources: mostly data from nationally representative household surveys (including national censuses) were used. Survey sources include Demographic and Health Surveys (DHS) and Living Standards Measurement Surveys (LSMS), Multi-Indicator Cluster Surveys (MICS), the World Health Survey (WHS), other nationally developed and implemented surveys, and various government agencies (for example, ministries of energy and utilities). Given the low frequency and the regional distribution of some surveys, a number of countries have gaps in available data. To develop the historical evolution and starting point of electrification rates, a simple modeling approach was adopted to fill in the missing data points - around 1990, around 2000, and around 2010. Therefore, a country can have a continuum of zero to three data points. There are 42 countries with zero data point and the weighted regional average was used as an estimate for electrification in each of the data periods. 170 countries have between one and three data points and missing data are estimated by using a model with region, country, and time variables. The model keeps the original observation if data is available for any of the time periods. This modeling approach allowed the estimation of electrification rates for 212 countries over these three time periods (Indicated as "Estimate"). Notation "Assumption" refers to the assumption of universal access in countries classified as developed by the United Nations. Data begins from the year in which the first survey data is available for each country.
--------
Topic: Environment: Energy production & use