<div class="alert alert-block alert-info">
<b>WDI Inventory: </b> 
   137 indicators in Topic 6: Environment

<b>Output: </b> 
    WDI Availability of Data in Topic 6: Environment (2000-2021)</div>

In [1]:
import os
import pandas as pd
import wbgapi as wb # https://github.com/tgherzog/wbgapi
import plotly.express as px
import plotly.graph_objects as go
import datetime
import numpy as np
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

In [2]:
# Define your own folder 
out_dir = os.path.join(os.path.expanduser('~'), 'Documents/Websites/JavierParada.github.io/Inventory/')
print(out_dir)

/Users/javierparada/Documents/Websites/JavierParada.github.io/Inventory/

## Check for recent updates in each of the 68 databases

In [3]:
# Check date for last update of WDI 2022-02-15
ListOfDict = list(wb.source.list())
Databases = pd.DataFrame(ListOfDict)
print("There are {} databases available.".format(len(Databases)))
print("{} was last updated on {}.".format(ListOfDict[1]['name'],ListOfDict[1]['lastupdated']))
Databases['lastupdated'] = pd.to_datetime(Databases['lastupdated'])
Databases.sort_values(by='lastupdated', ascending=False).head()

There are 68 databases available.
World Development Indicators was last updated on 2022-02-15.

,id,lastupdated,name,code,databid,description,url,dataavailability,metadataavailability,concepts
54,75,2022-02-22,"Environment, Social and Governance (ESG) Data",ESG,3711,,,Y,Y,3
31,40,2022-02-17,Population estimates and projections,HPP,3668,,,Y,Y,3
37,54,2022-02-17,Joint External Debt Hub,JED,1174,,,Y,,3
10,16,2022-02-16,Health Nutrition and Population Statistics,HNP,311,,,Y,Y,3
66,87,2022-02-16,Country Climate and Development Report (CCDR),CCD,3736,,,Y,Y,3

## 21 topics, 1,443 indicators in WDI, 135 in topic 6 Environment

In [4]:
# 21 topics
pd.DataFrame(list(wb.topic.list())).head(7)

,id,value,sourceNote
0,1,Agriculture & Rural Development,For the 70 percent of the world's poor who liv...
1,2,Aid Effectiveness,Aid effectiveness is the impact that aid has i...
2,3,Economy & Growth,Economic growth is central to economic develop...
3,4,Education,Education is one of the most powerful instrume...
4,5,Energy & Mining,The world economy needs ever-increasing amount...
5,6,Environment,Natural and man-made environmental resources –...
6,7,Financial Sector,An economy's financial markets are critical to...

In [5]:
others = ['EG.ELC.ACCS.RU.ZS', 'EG.ELC.ACCS.UR.ZS']
desc_others = pd.DataFrame(list(wb.series.list(others)))
desc = pd.DataFrame(list(wb.series.list(db=2, topic=6)))
desc = desc.append(desc_others)
desc = desc.rename({'id': 'variable', 'value':'description'}, axis=1)
desc = desc.sort_values(by='variable', ascending=True).reset_index(drop=True)
desc.to_csv('desc.csv')

# Environment 141

In [6]:
# List of indicators
others = ['EG.ELC.ACCS.RU.ZS', 'EG.ELC.ACCS.UR.ZS']
environment135 = sorted(list(wb.topic.members(6)) + others)
len(environment135)

141

In [7]:
environment135

['AG.LND.AGRI.ZS',
 'AG.LND.ARBL.ZS',
 'AG.LND.EL5M.RU.K2',
 'AG.LND.EL5M.RU.ZS',
 'AG.LND.EL5M.UR.K2',
 'AG.LND.EL5M.UR.ZS',
 'AG.LND.EL5M.ZS',
 'AG.LND.FRST.K2',
 'AG.LND.FRST.ZS',
 'AG.LND.PRCP.MM',
 'AG.LND.TOTL.K2',
 'AG.LND.TOTL.RU.K2',
 'AG.LND.TOTL.UR.K2',
 'AG.SRF.TOTL.K2',
 'EG.CFT.ACCS.ZS',
 'EG.EGY.PRIM.PP.KD',
 'EG.ELC.ACCS.RU.ZS',
 'EG.ELC.ACCS.UR.ZS',
 'EG.ELC.ACCS.ZS',
 'EG.ELC.FOSL.ZS',
 'EG.ELC.RNEW.ZS',
 'EG.ELC.RNWX.KH',
 'EG.ELC.RNWX.ZS',
 'EG.FEC.RNEW.ZS',
 'EN.ATM.CO2E.EG.ZS',
 'EN.ATM.CO2E.GF.KT',
 'EN.ATM.CO2E.GF.ZS',
 'EN.ATM.CO2E.KD.GD',
 'EN.ATM.CO2E.KT',
 'EN.ATM.CO2E.LF.KT',
 'EN.ATM.CO2E.LF.ZS',
 'EN.ATM.CO2E.PC',
 'EN.ATM.CO2E.PP.GD',
 'EN.ATM.CO2E.PP.GD.KD',
 'EN.ATM.CO2E.SF.KT',
 'EN.ATM.CO2E.SF.ZS',
 'EN.ATM.GHGO.KT.CE',
 'EN.ATM.GHGO.ZG',
 'EN.ATM.GHGT.KT.CE',
 'EN.ATM.GHGT.ZG',
 'EN.ATM.HFCG.KT.CE',
 'EN.ATM.METH.AG.KT.CE',
 'EN.ATM.METH.AG.ZS',
 'EN.ATM.METH.EG.KT.CE',
 'EN.ATM.METH.EG.ZS',
 'EN.ATM.METH.KT.CE',
 'EN.ATM.METH.ZG',
 'EN.ATM.NOXE.AG.KT.CE',
 'EN.ATM.NOXE.AG.ZS',
 'EN.ATM.NOXE.EG.KT.CE',
 'EN.ATM.NOXE.EG.ZS',
 'EN.ATM.NOXE.KT.CE',
 'EN.ATM.NOXE.ZG',
 'EN.ATM.PFCG.KT.CE',
 'EN.ATM.PM25.MC.M3',
 'EN.ATM.PM25.MC.T1.ZS',
 'EN.ATM.PM25.MC.T2.ZS',
 'EN.ATM.PM25.MC.T3.ZS',
 'EN.ATM.PM25.MC.ZS',
 'EN.ATM.SF6G.KT.CE',
 'EN.BIR.THRD.NO',
 'EN.CLC.DRSK.XQ',
 'EN.CLC.GHGR.MT.CE',
 'EN.CLC.MDAT.ZS',
 'EN.CO2.BLDG.ZS',
 'EN.CO2.ETOT.ZS',
 'EN.CO2.MANF.ZS',
 'EN.CO2.OTHX.ZS',
 'EN.CO2.TRAN.ZS',
 'EN.FSH.THRD.NO',
 'EN.HPT.THRD.NO',
 'EN.MAM.THRD.NO',
 'EN.POP.EL5M.RU.ZS',
 'EN.POP.EL5M.UR.ZS',
 'EN.POP.EL5M.ZS',
 'EN.POP.SLUM.UR.ZS',
 'ER.FSH.AQUA.MT',
 'ER.FSH.CAPT.MT',
 'ER.FSH.PROD.MT',
 'ER.GDP.FWTL.M3.KD',
 'ER.H2O.FWAG.ZS',
 'ER.H2O.FWDM.ZS',
 'ER.H2O.FWIN.ZS',
 'ER.H2O.FWST.ZS',
 'ER.H2O.FWTL.K3',
 'ER.H2O.FWTL.ZS',
 'ER.H2O.INTR.K3',
 'ER.H2O.INTR.PC',
 'ER.LND.PTLD.ZS',
 'ER.MRN.PTMR.ZS',
 'ER.PTD.TOTL.ZS',
 'NY.ADJ.AEDU.CD',
 'NY.ADJ.AEDU.GN.ZS',
 'NY.ADJ.DCO2.CD',
 'NY.ADJ.DCO2.GN.ZS',
 'NY.ADJ.DFOR.CD',
 'NY.ADJ.DFOR.GN.ZS',
 'NY.ADJ.DKAP.CD',
 'NY.ADJ.DKAP.GN.ZS',
 'NY.ADJ.DMIN.CD',
 'NY.ADJ.DMIN.GN.ZS',
 'NY.ADJ.DNGY.CD',
 'NY.ADJ.DNGY.GN.ZS',
 'NY.ADJ.DPEM.CD',
 'NY.ADJ.DPEM.GN.ZS',
 'NY.ADJ.ICTR.GN.ZS',
 'NY.ADJ.NNAT.CD',
 'NY.ADJ.NNAT.GN.ZS',
 'NY.ADJ.SVNG.CD',
 'NY.ADJ.SVNG.GN.ZS',
 'NY.ADJ.SVNX.CD',
 'NY.ADJ.SVNX.GN.ZS',
 'NY.GDP.COAL.RT.ZS',
 'NY.GDP.FRST.RT.ZS',
 'NY.GDP.MINR.RT.ZS',
 'NY.GDP.NGAS.RT.ZS',
 'NY.GDP.PETR.RT.ZS',
 'NY.GDP.TOTL.RT.ZS',
 'SH.H2O.BASW.RU.ZS',
 'SH.H2O.BASW.UR.ZS',
 'SH.H2O.BASW.ZS',
 'SH.H2O.SMDW.RU.ZS',
 'SH.H2O.SMDW.UR.ZS',
 'SH.H2O.SMDW.ZS',
 'SH.STA.AIRP.P5',
 'SH.STA.BASS.RU.ZS',
 'SH.STA.BASS.UR.ZS',
 'SH.STA.BASS.ZS',
 'SH.STA.HYGN.RU.ZS',
 'SH.STA.HYGN.UR.ZS',
 'SH.STA.HYGN.ZS',
 'SH.STA.ODFC.RU.ZS',
 'SH.STA.ODFC.UR.ZS',
 'SH.STA.ODFC.ZS',
 'SH.STA.POIS.P5',
 'SH.STA.POIS.P5.FE',
 'SH.STA.POIS.P5.MA',
 'SH.STA.SMSS.RU.ZS',
 'SH.STA.SMSS.UR.ZS',
 'SH.STA.SMSS.ZS',
 'SH.STA.WASH.P5']

In [8]:
# Includes TWN
countries = sorted(list(wb.region.members('WLD')))
countries.remove("TWN")
len(countries)

217

In [9]:
file_excel = "countries217.csv"
wikipedia = pd.read_csv(os.path.join(out_dir, file_excel))
wikipedia = wikipedia.rename({'Code': 'economy'}, axis=1)
wikipedia.head()

,Original order,economy,Country,Order,Continent,Wikipedia
0,1,AFG,Afghanistan,102,Asia,https://en.wikipedia.org/wiki/Afghanistan
1,2,ALB,Albania,75,Europe,https://en.wikipedia.org/wiki/Albania
2,3,DZA,Algeria,141,Africa,https://en.wikipedia.org/wiki/Algeria
3,4,ASM,American Samoa,A1,Other,https://en.wikipedia.org/wiki/American_Samoa
4,5,AND,Andorra,62,Europe,https://en.wikipedia.org/wiki/Andorra

In [10]:
appended_data = []
for count, variable in enumerate(environment135, start=1):

    df = wb.data.DataFrame(series = variable, 
                    economy = countries, 
                    time = range(2000, 2023, 1), 
                    db=2, labels=True).reset_index()
    clean = df.dropna(how='all', axis=1)
    last = clean.columns[-1]
    print(count, variable, last, sep='\t')

    df["variable"] = variable
    # print("Done")
    appended_data.append(df)
    
appended_data = pd.concat(appended_data)
# appended_data.to_excel('appended.xlsx')

1	AG.LND.AGRI.ZS	YR2018
2	AG.LND.ARBL.ZS	YR2018
3	AG.LND.EL5M.RU.K2	YR2010
4	AG.LND.EL5M.RU.ZS	YR2010
5	AG.LND.EL5M.UR.K2	YR2010
6	AG.LND.EL5M.UR.ZS	YR2010
7	AG.LND.EL5M.ZS	YR2010
8	AG.LND.FRST.K2	YR2020
9	AG.LND.FRST.ZS	YR2020
10	AG.LND.PRCP.MM	YR2017
11	AG.LND.TOTL.K2	YR2020
12	AG.LND.TOTL.RU.K2	YR2010
13	AG.LND.TOTL.UR.K2	YR2010
14	AG.SRF.TOTL.K2	YR2018
15	EG.CFT.ACCS.ZS	YR2019
16	EG.EGY.PRIM.PP.KD	YR2015
17	EG.ELC.ACCS.RU.ZS	YR2019
18	EG.ELC.ACCS.UR.ZS	YR2019
19	EG.ELC.ACCS.ZS	YR2019
20	EG.ELC.FOSL.ZS	YR2015
21	EG.ELC.RNEW.ZS	YR2019
22	EG.ELC.RNWX.KH	YR2015
23	EG.ELC.RNWX.ZS	YR2015
24	EG.FEC.RNEW.ZS	YR2018
25	EN.ATM.CO2E.EG.ZS	YR2015
26	EN.ATM.CO2E.GF.KT	YR2016
27	EN.ATM.CO2E.GF.ZS	YR2016
28	EN.ATM.CO2E.KD.GD	YR2018
29	EN.ATM.CO2E.KT	YR2018
30	EN.ATM.CO2E.LF.KT	YR2016
31	EN.ATM.CO2E.LF.ZS	YR2016
32	EN.ATM.CO2E.PC	YR2018
33	EN.ATM.CO2E.PP.GD	YR2018
34	EN.ATM.CO2E.PP.GD.KD	YR2018
35	EN.ATM.CO2E.SF.KT	YR2016
36	EN.ATM.CO2E.SF.ZS	YR2016
37	EN.ATM.GHGO.KT.CE	YR2016
38	EN.ATM.GHGO.ZG	YR2012
39	EN.ATM.GHGT.KT.CE	YR2018
40	EN.ATM.GHGT.ZG	YR2012
41	EN.ATM.HFCG.KT.CE	YR2010
42	EN.ATM.METH.AG.KT.CE	YR2018
43	EN.ATM.METH.AG.ZS	YR2008
44	EN.ATM.METH.EG.KT.CE	YR2018
45	EN.ATM.METH.EG.ZS	YR2008
46	EN.ATM.METH.KT.CE	YR2018
47	EN.ATM.METH.ZG	YR2012
48	EN.ATM.NOXE.AG.KT.CE	YR2018
49	EN.ATM.NOXE.AG.ZS	YR2008
50	EN.ATM.NOXE.EG.KT.CE	YR2018
51	EN.ATM.NOXE.EG.ZS	YR2008
52	EN.ATM.NOXE.KT.CE	YR2018
53	EN.ATM.NOXE.ZG	YR2012
54	EN.ATM.PFCG.KT.CE	YR2010
55	EN.ATM.PM25.MC.M3	YR2017
56	EN.ATM.PM25.MC.T1.ZS	YR2017
57	EN.ATM.PM25.MC.T2.ZS	YR2017
58	EN.ATM.PM25.MC.T3.ZS	YR2017
59	EN.ATM.PM25.MC.ZS	YR2017
60	EN.ATM.SF6G.KT.CE	YR2010
61	EN.BIR.THRD.NO	YR2018
62	EN.CLC.DRSK.XQ	YR2011
63	EN.CLC.GHGR.MT.CE	YR2009
64	EN.CLC.MDAT.ZS	YR2009
65	EN.CO2.BLDG.ZS	YR2014
66	EN.CO2.ETOT.ZS	YR2014
67	EN.CO2.MANF.ZS	YR2014
68	EN.CO2.OTHX.ZS	YR2014
69	EN.CO2.TRAN.ZS	YR2014
70	EN.FSH.THRD.NO	YR2018
71	EN.HPT.THRD.NO	YR2018
72	EN.MAM.THRD.NO	YR2018
73	EN.POP.EL5M.RU.ZS	YR2010
74	EN.POP.EL5M.UR.ZS	YR2010
75	EN.POP.EL5M.ZS	YR2010
76	EN.POP.SLUM.UR.ZS	YR2018
77	ER.FSH.AQUA.MT	YR2018
78	ER.FSH.CAPT.MT	YR2018
79	ER.FSH.PROD.MT	YR2018
80	ER.GDP.FWTL.M3.KD	YR2017
81	ER.H2O.FWAG.ZS	YR2017
82	ER.H2O.FWDM.ZS	YR2017
83	ER.H2O.FWIN.ZS	YR2017
84	ER.H2O.FWST.ZS	YR2017
85	ER.H2O.FWTL.K3	YR2017
86	ER.H2O.FWTL.ZS	YR2017
87	ER.H2O.INTR.K3	YR2017
88	ER.H2O.INTR.PC	YR2017
89	ER.LND.PTLD.ZS	YR2018
90	ER.MRN.PTMR.ZS	YR2018
91	ER.PTD.TOTL.ZS	YR2018
92	NY.ADJ.AEDU.CD	YR2019
93	NY.ADJ.AEDU.GN.ZS	YR2019
94	NY.ADJ.DCO2.CD	YR2019
95	NY.ADJ.DCO2.GN.ZS	YR2019
96	NY.ADJ.DFOR.CD	YR2019
97	NY.ADJ.DFOR.GN.ZS	YR2019
98	NY.ADJ.DKAP.CD	YR2019
99	NY.ADJ.DKAP.GN.ZS	YR2019
100	NY.ADJ.DMIN.CD	YR2019
101	NY.ADJ.DMIN.GN.ZS	YR2019
102	NY.ADJ.DNGY.CD	YR2019
103	NY.ADJ.DNGY.GN.ZS	YR2019
104	NY.ADJ.DPEM.CD	YR2019
105	NY.ADJ.DPEM.GN.ZS	YR2019
106	NY.ADJ.ICTR.GN.ZS	YR2019
107	NY.ADJ.NNAT.CD	YR2019
108	NY.ADJ.NNAT.GN.ZS	YR2019
109	NY.ADJ.SVNG.CD	YR2019
110	NY.ADJ.SVNG.GN.ZS	YR2019
111	NY.ADJ.SVNX.CD	YR2019
112	NY.ADJ.SVNX.GN.ZS	YR2019
113	NY.GDP.COAL.RT.ZS	YR2019
114	NY.GDP.FRST.RT.ZS	YR2019
115	NY.GDP.MINR.RT.ZS	YR2019
116	NY.GDP.NGAS.RT.ZS	YR2019
117	NY.GDP.PETR.RT.ZS	YR2019
118	NY.GDP.TOTL.RT.ZS	YR2019
119	SH.H2O.BASW.RU.ZS	YR2020
120	SH.H2O.BASW.UR.ZS	YR2020
121	SH.H2O.BASW.ZS	YR2020
122	SH.H2O.SMDW.RU.ZS	YR2020
123	SH.H2O.SMDW.UR.ZS	YR2020
124	SH.H2O.SMDW.ZS	YR2020
125	SH.STA.AIRP.P5	YR2016
126	SH.STA.BASS.RU.ZS	YR2020
127	SH.STA.BASS.UR.ZS	YR2020
128	SH.STA.BASS.ZS	YR2020
129	SH.STA.HYGN.RU.ZS	YR2020
130	SH.STA.HYGN.UR.ZS	YR2020
131	SH.STA.HYGN.ZS	YR2020
132	SH.STA.ODFC.RU.ZS	YR2020
133	SH.STA.ODFC.UR.ZS	YR2020
134	SH.STA.ODFC.ZS	YR2020
135	SH.STA.POIS.P5	YR2019
136	SH.STA.POIS.P5.FE	YR2019
137	SH.STA.POIS.P5.MA	YR2019
138	SH.STA.SMSS.RU.ZS	YR2020
139	SH.STA.SMSS.UR.ZS	YR2020
140	SH.STA.SMSS.ZS	YR2020
141	SH.STA.WASH.P5	YR2016

In [11]:
# add 2021 because it's empty right now
appended_data['YR2021'] = np.nan
appended_data['YR2022'] = np.nan
appended_data['YR2023'] = np.nan
appended_data.head()

,economy,Country,YR2000,YR2001,YR2002,YR2003,YR2004,YR2005,YR2006,YR2007,YR2008,YR2009,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,variable,YR2021,YR2022,YR2023
0,ZWE,Zimbabwe,38.929818,39.395114,39.989660,40.454957,41.359700,41.618198,42.135195,41.876696,42.522942,42.135195,41.876696,42.393693,41.876696,41.876696,41.876696,41.876696,41.876696,41.876696,41.876696,NaN,NaN,AG.LND.AGRI.ZS,NaN,NaN,NaN
1,ZMB,Zambia,30.264061,30.340736,30.422793,30.816933,30.800791,30.619190,31.003914,30.917822,31.056377,31.727626,31.525848,31.794886,32.063923,31.929404,32.063923,32.063923,32.063923,32.063923,32.063923,NaN,NaN,AG.LND.AGRI.ZS,NaN,NaN,NaN
2,ZAF,South Africa,80.888475,80.796149,80.808514,80.726080,80.462291,80.359248,79.868765,79.870414,80.050120,79.951199,79.871238,79.445054,79.417850,79.417850,79.417850,79.417850,79.417850,79.417850,79.417850,NaN,NaN,AG.LND.AGRI.ZS,NaN,NaN,NaN
3,YEM,"Yemen, Rep.",44.830199,44.690039,44.805576,44.500635,44.618065,44.553668,44.750649,44.750649,44.542304,44.419190,44.659734,44.419190,44.511999,44.508211,44.418433,44.382446,44.293805,44.297403,44.297403,NaN,NaN,AG.LND.AGRI.ZS,NaN,NaN,NaN
4,XKX,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.356021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AG.LND.AGRI.ZS,NaN,NaN,NaN

In [12]:
tableau = appended_data.groupby('variable').count().reset_index()
tableau[['CETS1','CETS2','CETS3','CETS4','CETS5','CETS6']] = tableau['variable'].str.split(expand=True, pat='.')
tableau = tableau.merge(desc, left_on='variable', right_on='variable', suffixes=('_left', '_right')) 
tableau["row"] = tableau['variable'] +": "+ tableau['description']
#tableau.set_index('variable', inplace=True)
#tableau = tableau[tableau["CETS3"] == "EL5M"]
tableau

,variable,economy,Country,YR2000,YR2001,YR2002,YR2003,YR2004,YR2005,YR2006,YR2007,YR2008,YR2009,YR2010,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,CETS1,CETS2,CETS3,CETS4,CETS5,CETS6,description,row
0,AG.LND.AGRI.ZS,217,217,206,206,206,206,206,206,208,209,208,208,208,210,210,210,210,210,210,209,209,0,0,0,0,0,AG,LND,AGRI,ZS,None,None,Agricultural land (% of land area),AG.LND.AGRI.ZS: Agricultural land (% of land a...
1,AG.LND.ARBL.ZS,217,217,204,204,204,204,204,204,206,207,206,206,206,207,207,207,207,207,206,205,205,0,0,0,0,0,AG,LND,ARBL,ZS,None,None,Arable land (% of land area),AG.LND.ARBL.ZS: Arable land (% of land area)
2,AG.LND.EL5M.RU.K2,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,RU,K2,None,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.K2: Rural land area where eleva...
3,AG.LND.EL5M.RU.ZS,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,RU,ZS,None,Rural land area where elevation is below 5 met...,AG.LND.EL5M.RU.ZS: Rural land area where eleva...
4,AG.LND.EL5M.UR.K2,217,217,179,0,0,0,0,0,0,0,0,0,179,0,0,0,0,0,0,0,0,0,0,0,0,0,AG,LND,EL5M,UR,K2,None,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2: Urban land area where eleva...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,SH.STA.POIS.P5.MA,217,217,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,0,0,0,0,SH,STA,POIS,P5,MA,None,Mortality rate attributed to unintentional poi...,SH.STA.POIS.P5.MA: Mortality rate attributed t...
137,SH.STA.SMSS.RU.ZS,217,217,75,76,77,77,77,77,78,78,78,78,78,78,78,78,78,78,78,78,78,77,77,0,0,0,SH,STA,SMSS,RU,ZS,None,People using safely managed sanitation service...,SH.STA.SMSS.RU.ZS: People using safely managed...
138,SH.STA.SMSS.UR.ZS,217,217,97,98,98,98,98,98,99,99,99,99,99,99,99,99,99,99,99,99,99,98,98,0,0,0,SH,STA,SMSS,UR,ZS,None,People using safely managed sanitation service...,SH.STA.SMSS.UR.ZS: People using safely managed...
139,SH.STA.SMSS.ZS,217,217,120,122,123,123,123,124,125,125,125,126,126,126,126,126,126,126,126,125,124,121,120,0,0,0,SH,STA,SMSS,ZS,None,None,People using safely managed sanitation service...,SH.STA.SMSS.ZS: People using safely managed sa...
140,SH.STA.WASH.P5,217,217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,183,0,0,0,0,0,0,0,SH,STA,WASH,P5,None,None,"Mortality rate attributed to unsafe water, uns...",SH.STA.WASH.P5: Mortality rate attributed to u...

In [13]:
counts = tableau[['CETS1','CETS2','CETS3','CETS4','CETS5']].value_counts().to_frame('counts')
counts.sort_values(by=['CETS1','CETS2','CETS3','CETS4','CETS5'], ascending=True)

                               counts
CETS1 CETS2 CETS3 CETS4 CETS5
AG    LND   EL5M  RU    K2          1
                        ZS          1
                  UR    K2          1
                        ZS          1
            TOTL  RU    K2          1
...                               ...
SH    STA   ODFC  UR    ZS          1
            POIS  P5    FE          1
                        MA          1
            SMSS  RU    ZS          1
                  UR    ZS          1

[74 rows x 1 columns]

In [14]:
columns = ['YR2000', 'YR2001', 'YR2002','YR2003', 'YR2004', 'YR2005', 'YR2006', 'YR2007', 'YR2008', 'YR2009',
           'YR2010', 'YR2011', 'YR2012', 'YR2013', 'YR2014', 'YR2015', 'YR2016','YR2017', 'YR2018', 'YR2019', 'YR2020', 'YR2021', 'YR2022', 'YR2023']

In [15]:
pd.options.display.float_format = '{:,.1f}'.format
percentages = tableau[columns]/217*100
data = percentages.values.round(1)

In [16]:
fig = px.imshow(data,
                labels=dict(x = "Year", y = "Indicator", color = "Available"),
                x = columns,
                y = tableau["row"].tolist(), 
                width=1500, height=3000,
                color_continuous_scale = "portland_r"
               )
fig.update_layout(
    title='WDI Availability of Data in Topic 6: Environment (2000-2022)',
    coloraxis_colorbar=dict(
    thicknessmode="pixels", thickness=70,
    lenmode="pixels", len=400,
    yanchor="top", y=.95,
    ticks="outside", ticksuffix=" %",
    dtick=5)
)
fig.update_xaxes(side="top")
fig.write_html("../WDIinventory.html")
fig.write_json("../WDIinventory.json", pretty=True)

<div class="alert alert-block alert-info">
February 28, 2022</div>

In [17]:
list_0 = ['EN.ATM.CO2E.KD.GD', 'EN.ATM.CO2E.KT', 'EN.ATM.CO2E.PC', 'EN.ATM.CO2E.PP.GD', 'EN.ATM.CO2E.PP.GD.KD', 'EN.ATM.GHGT.KT.CE', 'EN.ATM.METH.AG.KT.CE', 'EN.ATM.METH.EG.KT.CE', 'EN.ATM.METH.KT.CE', 'EN.ATM.NOXE.AG.KT.CE', 'EN.ATM.NOXE.EG.KT.CE', 'EN.ATM.NOXE.KT.CE']
list_1 = ['EN.ATM.CO2E.EG.ZS', 'EN.ATM.CO2E.GF.KT', 'EN.ATM.CO2E.GF.ZS', 'EN.ATM.CO2E.KD.GD', 'EN.ATM.CO2E.KT', 'EN.ATM.CO2E.LF.KT', 'EN.ATM.CO2E.LF.ZS', 'EN.ATM.CO2E.PC', 'EN.ATM.CO2E.PP.GD', 'EN.ATM.CO2E.PP.GD.KD', 'EN.ATM.CO2E.SF.KT', 'EN.ATM.CO2E.SF.ZS', 'EN.ATM.GHGO.KT.CE', 'EN.ATM.GHGO.ZG', 'EN.ATM.GHGT.KT.CE', 'EN.ATM.GHGT.ZG', 'EN.ATM.HFCG.KT.CE', 'EN.ATM.METH.AG.KT.CE', 'EN.ATM.METH.AG.ZS', 'EN.ATM.METH.EG.KT.CE', 'EN.ATM.METH.EG.ZS', 'EN.ATM.METH.KT.CE', 'EN.ATM.METH.ZG', 'EN.ATM.NOXE.AG.KT.CE', 'EN.ATM.NOXE.AG.ZS', 'EN.ATM.NOXE.EG.KT.CE', 'EN.ATM.NOXE.EG.ZS', 'EN.ATM.NOXE.KT.CE', 'EN.ATM.NOXE.ZG', 'EN.ATM.PFCG.KT.CE', 'EN.ATM.PM25.MC.M3', 'EN.ATM.PM25.MC.T1.ZS', 'EN.ATM.PM25.MC.T2.ZS', 'EN.ATM.PM25.MC.T3.ZS', 'EN.ATM.PM25.MC.ZS', 'EN.ATM.SF6G.KT.CE', 'EN.CLC.DRSK.XQ', 'EN.CLC.GHGR.MT.CE', 'EN.CLC.MDAT.ZS', 'EN.CO2.BLDG.ZS', 'EN.CO2.ETOT.ZS', 'EN.CO2.MANF.ZS', 'EN.CO2.OTHX.ZS', 'EN.CO2.TRAN.ZS']
list_1 = [fruit for fruit in list_1 if fruit not in list_0]
list_2 = ['ER.LND.PTLD.ZS', 'ER.MRN.PTMR.ZS', 'ER.PTD.TOTL.ZS']
list_3 = ['EN.FSH.THRD.NO', 'EN.BIR.THRD.NO', 'EN.HPT.THRD.NO', 'EN.MAM.THRD.NO']
list_4 = ['ER.GDP.FWTL.M3.KD', 'ER.H2O.FWAG.ZS', 'ER.H2O.FWDM.ZS', 'ER.H2O.FWIN.ZS', 'ER.H2O.FWST.ZS', 'ER.H2O.FWTL.K3', 'ER.H2O.FWTL.ZS', 'ER.H2O.INTR.K3', 'ER.H2O.INTR.PC']
list_5 = ['AG.LND.EL5M.RU.K2', 'AG.LND.EL5M.RU.ZS', 'AG.LND.EL5M.UR.K2', 'AG.LND.EL5M.UR.ZS', 'AG.LND.EL5M.ZS', 'EN.POP.EL5M.RU.ZS', 'EN.POP.EL5M.UR.ZS', 'EN.POP.EL5M.ZS']
list_6 = ['AG.LND.AGRI.ZS', 'AG.LND.ARBL.ZS', 'AG.LND.FRST.K2', 'AG.LND.FRST.ZS', 'AG.LND.TOTL.K2', 'AG.LND.TOTL.RU.K2', 'AG.LND.TOTL.UR.K2', 'AG.SRF.TOTL.K2', 'AG.LND.PRCP.MM']
list_7 = ['ER.FSH.AQUA.MT', 'ER.FSH.CAPT.MT', 'ER.FSH.PROD.MT']
list_8 = ['EG.ELC.ACCS.RU.ZS', 'EG.ELC.ACCS.UR.ZS', 'EG.ELC.ACCS.ZS', 'EG.FEC.RNEW.ZS', 'EG.EGY.PRIM.PP.KD', 'EG.ELC.FOSL.ZS', 'EG.ELC.RNWX.KH', 'EG.ELC.RNWX.ZS', 'EG.ELC.RNEW.ZS']
list_9 = ['EG.CFT.ACCS.ZS', 'EN.POP.SLUM.UR.ZS', 'SH.STA.SMSS.RU.ZS', 'SH.STA.SMSS.UR.ZS', 'SH.STA.SMSS.ZS', 'SH.H2O.BASW.RU.ZS', 'SH.H2O.BASW.UR.ZS', 'SH.H2O.BASW.ZS', 'SH.H2O.SMDW.RU.ZS', 'SH.H2O.SMDW.UR.ZS', 'SH.H2O.SMDW.ZS', 'SH.STA.BASS.RU.ZS', 'SH.STA.BASS.UR.ZS', 'SH.STA.BASS.ZS', 'SH.STA.HYGN.RU.ZS', 'SH.STA.HYGN.UR.ZS', 'SH.STA.HYGN.ZS', 'SH.STA.ODFC.RU.ZS', 'SH.STA.ODFC.UR.ZS', 'SH.STA.ODFC.ZS', 'SH.STA.AIRP.P5', 'SH.STA.POIS.P5', 'SH.STA.POIS.P5.FE', 'SH.STA.POIS.P5.MA', 'SH.STA.WASH.P5']
subcategories = [list_0, list_1, list_2, list_3, list_4, list_5, list_6, list_7, list_8, list_9]
flat_list = [item for sublist in subcategories for item in sublist]

In [18]:
len(flat_list)

114

In [19]:
for i in range(0,10):   
    df = tableau[tableau["variable"].isin(subcategories[i])]
    percentages = df[columns]/217*100
    data = percentages.values.round(1)
    fig = px.imshow(data,
                labels=dict(x = "Year", y = "Indicator", color = "Available"),
                x = columns,
                y = df["row"].tolist(),  
                color_continuous_scale = "portland_r"
               )
    fig.update_layout(
        title='WDI Availability of Data in Topic 6: Environment (2000-2022)',
        coloraxis_colorbar=dict(
            thicknessmode="pixels", thickness=70,
            lenmode="pixels", len=400,
            yanchor="top", y=.95,
            ticks="outside", ticksuffix=" %",
            dtick=5)
    )
    fig.update_xaxes(side="top")
    
    fig.write_html("../WDIinventory_{}.html".format(i))

# Notes

https://stackoverflow.com/questions/64778606/plotly-heatmap-color-legend-i-subplothttps://stackoverflow.com/questions/64778606/plotly-heatmap-color-legend-i-subplot

df = wb.data.DataFrame(series = 'EG.ELC.ACCS.RU.ZS', 
                    economy=countries, 
                    time=range(2000, 2021, 1), 
                    db=2, labels=True).reset_index()

In [20]:
df = wb.data.DataFrame('EG.ELC.ACCS.ZS', wb.region.members('WLD'), time=range(2000, 2021, 1), labels=True)

In [21]:
wb.series.metadata.get('EG.ELC.ACCS.ZS', economies=['KEN', 'TZA'])

========
Series: EG.ELC.ACCS.ZS

Aggregationmethod: Weighted Average
--------
Developmentrelevance: Maintaining reliable and secure electricity services while seeking to rapidly decarbonize power systems is a key challenge for countries throughout the world. More and more countries are becoming increasing dependent on reliable and secure electricity supplies to underpin economic growth and community prosperity. This reliance is set to grow as more efficient and less carbon intensive forms of power are developed and deployed to help decarbonize economies.

Energy is necessary for creating the conditions for economic growth. It is impossible to operate a factory, run a shop, grow crops or deliver goods to consumers without using some form of energy. Access to electricity is particularly crucial to human development as electricity is, in practice, indispensable for certain basic activities, such as lighting, refrigeration and the running of household appliances, and cannot easily be replaced by other forms of energy. Individuals' access to electricity is one of the most clear and un-distorted indication of a country's energy poverty status.

Electricity access is increasingly at the forefront of governments' preoccupations, especially in the developing countries. As a consequence, a lot of rural electrification programs and national electrification agencies have been created in these countries to monitor more accurately the needs and the status of rural development and electrification.

Use of energy is important in improving people's standard of living. But electricity generation also can damage the environment. Whether such damage occurs depends largely on how electricity is generated. For example, burning coal releases twice as much carbon dioxide - a major contributor to global warming - as does burning an equivalent amount of natural gas.
--------
IndicatorName: Access to electricity (% of population)
--------
License_Type: CC BY-4.0
--------
License_URL: https://datacatalog.worldbank.org/public-licenses#cc-by
--------
Longdefinition: Access to electricity is the percentage of population with access to electricity. Electrification data are collected from industry, national surveys and international sources.
--------
Periodicity: Annual
--------
Source: World Bank Global Electrification Database from "Tracking SDG 7: The Energy Progress Report" led jointly by the custodian agencies: the International Energy Agency (IEA), the International Renewable Energy Agency (IRENA), the United Nations Statistics Division (UNSD), the World Bank and the World Health Organization (WHO).
--------
Statisticalconceptandmethodology: Data for access to electricity are collected among different sources: mostly data from nationally representative household surveys (including national censuses) were used. Survey sources include Demographic and Health Surveys (DHS) and Living Standards Measurement Surveys (LSMS), Multi-Indicator Cluster Surveys (MICS), the World Health Survey (WHS), other nationally developed and implemented surveys, and various government agencies (for example, ministries of energy and utilities). Given the low frequency and the regional distribution of some surveys, a number of countries have gaps in available data. To develop the historical evolution and starting point of electrification rates, a simple modeling approach was adopted to fill in the missing data points - around 1990, around 2000, and around 2010. Therefore, a country can have a continuum of zero to three data points. There are 42 countries with zero data point and the weighted regional average was used as an estimate for electrification in each of the data periods. 170 countries have between one and three data points and missing data are estimated by using a model with region, country, and time variables. The model keeps the original observation if data is available for any of the time periods. This modeling approach allowed the estimation of electrification rates for 212 countries over these three time periods (Indicated as "Estimate"). Notation "Assumption" refers to the assumption of universal access in countries classified as developed by the United Nations. Data begins from the year in which the first survey data is available for each country.
--------
Topic: Environment: Energy production & use